// <auto-generated />
using System;
using GymCrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymCrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GymCrmDbContext))]
    partial class GymCrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymCrm.Domain.Attendance.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("MarkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarkedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("TrainingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarkedByUserId");

                    b.HasIndex("GroupId", "TrainingDate");

                    b.HasIndex("ClientId", "GroupId", "TrainingDate")
                        .IsUnique();

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("GymCrm.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MessengerPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MessengerPlatformUserIdHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Web");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("MessengerPlatform");

                    b.HasIndex("Source");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("GymCrm.Domain.Bot.BotIdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlatformUserIdHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Platform", "PlatformUserIdHash", "IdempotencyKey", "ActionType")
                        .IsUnique();

                    b.ToTable("BotIdempotencyRecords", t =>
                        {
                            t.HasCheckConstraint("CK_BotIdempotencyRecords_RequiredValues", "btrim(\"Platform\") <> '' AND btrim(\"PlatformUserIdHash\") <> '' AND btrim(\"IdempotencyKey\") <> '' AND btrim(\"ActionType\") <> '' AND btrim(\"PayloadHash\") <> '' AND btrim(\"Status\") <> ''");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("GymCrm.Domain.Branches.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsProfessional")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("PhotoSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PhotoUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfessionalComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("FirstName");

                    b.HasIndex("IsProfessional");

                    b.HasIndex("LastName");

                    b.HasIndex("Phone");

                    b.HasIndex("Status");

                    b.ToTable("Clients", t =>
                        {
                            t.HasCheckConstraint("CK_Clients_PhotoSizeBytes_NonNegative", "\"PhotoSizeBytes\" IS NULL OR \"PhotoSizeBytes\" >= 0");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientBranchAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ClientId", "ValidFrom", "ValidTo");

                    b.ToTable("ClientBranchAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_ClientBranchAssignments_Period_NonEmpty", "\"ValidTo\" IS NULL OR \"ValidTo\" > \"ValidFrom\"");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientContacts");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PlatformUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlatformUserIdHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UnlinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformUserIdHash");

                    b.HasIndex("ClientId", "Platform")
                        .IsUnique()
                        .HasFilter("\"UnlinkedAt\" IS NULL");

                    b.HasIndex("Platform", "PlatformUserId")
                        .IsUnique()
                        .HasFilter("\"UnlinkedAt\" IS NULL");

                    b.ToTable("ClientMessengerAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_ClientMessengerAccounts_RequiredValues", "btrim(\"PlatformUserId\") <> '' AND btrim(\"PlatformUserIdHash\") <> ''");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerLinkToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedByPlatformUserIdHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ClientId", "Platform", "ExpiresAt");

                    b.HasIndex("Platform", "UsedAt");

                    b.ToTable("ClientMessengerLinkTokens", t =>
                        {
                            t.HasCheckConstraint("CK_ClientMessengerLinkTokens_RequiredValues", "btrim(\"TokenHash\") <> ''");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdempotencyPayloadHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TelegramUpdateId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUserIdHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ClientId", "Platform", "CreatedAt");

                    b.HasIndex("ClientId", "Platform", "Direction", "CreatedAt");

                    b.HasIndex("ClientId", "Platform", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL AND btrim(\"IdempotencyKey\") <> ''");

                    b.HasIndex("Platform", "TelegramUpdateId")
                        .IsUnique()
                        .HasFilter("\"TelegramUpdateId\" IS NOT NULL");

                    b.HasIndex("Platform", "TelegramChatId", "TelegramMessageId")
                        .IsUnique()
                        .HasFilter("\"TelegramMessageId\" IS NOT NULL AND \"TelegramChatId\" IS NOT NULL AND btrim(\"TelegramChatId\") <> ''");

                    b.ToTable("ClientMessengerMessages", t =>
                        {
                            t.HasCheckConstraint("CK_ClientMessengerMessages_Text_Required", "btrim(\"Text\") <> ''");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerReadState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClientId", "Platform", "UserId")
                        .IsUnique();

                    b.ToTable("ClientMessengerReadStates");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientTelegramPollState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("NextUpdateOffset")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BotName")
                        .IsUnique();

                    b.ToTable("ClientTelegramPollStates", t =>
                        {
                            t.HasCheckConstraint("CK_ClientTelegramPollStates_BotName_Required", "btrim(\"BotName\") <> ''");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaidByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SingleVisitUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("PaidByUserId");

                    b.HasIndex("SaleId");

                    b.HasIndex("ValidTo");

                    b.ToTable("ClientMemberships", t =>
                        {
                            t.HasCheckConstraint("CK_ClientMemberships_PaymentAmount_NonNegative", "\"PaymentAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembershipRefund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CanceledByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RefundDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanceledAt");

                    b.HasIndex("CanceledByUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RefundDate");

                    b.HasIndex("SaleId");

                    b.ToTable("ClientMembershipRefunds", t =>
                        {
                            t.HasCheckConstraint("CK_ClientMembershipRefunds_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembershipSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PurchaseDate");

                    b.ToTable("ClientMembershipSales", t =>
                        {
                            t.HasCheckConstraint("CK_ClientMembershipSales_GrossAmount_NonNegative", "\"GrossAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.ClientGroup", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.HasKey("ClientId", "GroupId");

                    b.HasIndex("BranchId");

                    b.HasIndex("GroupId", "BranchId");

                    b.ToTable("ClientGroups");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.ClientGroupAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ClientId", "GroupId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("ClientId", "GroupId", "ValidFrom", "ValidTo");

                    b.ToTable("ClientGroupAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_ClientGroupAssignments_Period_NonEmpty", "\"ValidTo\" IS NULL OR \"ValidTo\" > \"ValidFrom\"");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.GroupTrainer", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("GroupTrainers");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.GroupTrainerAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("TrainerId", "GroupId")
                        .IsUnique()
                        .HasFilter("\"ValidTo\" IS NULL");

                    b.HasIndex("TrainerId", "GroupId", "ValidFrom", "ValidTo");

                    b.ToTable("GroupTrainerAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_GroupTrainerAssignments_Period_NonEmpty", "\"ValidTo\" IS NULL OR \"ValidTo\" > \"ValidFrom\"");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.GroupType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GroupTypes");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.TrainingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeOnly>("TrainingStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("Weekdays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("GroupTypeId");

                    b.HasIndex("HallId");

                    b.HasIndex("Name");

                    b.HasIndex("HallId", "BranchId");

                    b.ToTable("TrainingGroups", t =>
                        {
                            t.HasCheckConstraint("CK_TrainingGroups_DurationMinutes_Range", "\"DurationMinutes\" >= 1 AND \"DurationMinutes\" <= 180");

                            t.HasCheckConstraint("CK_TrainingGroups_Weekdays_NotEmpty", "cardinality(\"Weekdays\") >= 1");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MessengerPlatform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MessengerPlatformUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("MessengerPlatform", "MessengerPlatformUserId")
                        .IsUnique()
                        .HasFilter("\"MessengerPlatform\" IS NOT NULL AND \"MessengerPlatformUserId\" IS NOT NULL AND btrim(\"MessengerPlatformUserId\") <> ''");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_MessengerIdentity_Consistency", "(\"MessengerPlatform\" IS NULL AND (\"MessengerPlatformUserId\" IS NULL OR btrim(\"MessengerPlatformUserId\") = '')) OR (\"MessengerPlatform\" = 'Telegram' AND \"MessengerPlatformUserId\" IS NOT NULL AND btrim(\"MessengerPlatformUserId\") <> '')");
                        });
                });

            modelBuilder.Entity("GymCrm.Domain.Attendance.Attendance", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("AttendanceEntries")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Groups.TrainingGroup", "Group")
                        .WithMany("AttendanceEntries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "MarkedByUser")
                        .WithMany("AttendanceMarks")
                        .HasForeignKey("MarkedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Group");

                    b.Navigation("MarkedByUser");
                });

            modelBuilder.Entity("GymCrm.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("GymCrm.Domain.Users.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymCrm.Domain.Branches.Hall", b =>
                {
                    b.HasOne("GymCrm.Domain.Branches.Branch", "Branch")
                        .WithMany("Halls")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.Client", b =>
                {
                    b.HasOne("GymCrm.Domain.Branches.Branch", "Branch")
                        .WithMany("Clients")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientBranchAssignment", b =>
                {
                    b.HasOne("GymCrm.Domain.Branches.Branch", "Branch")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("BranchAssignments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedClientBranchAssignments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientContact", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerAccount", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("MessengerAccounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerLinkToken", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("MessengerLinkTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedMessengerLinkTokens")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerMessage", b =>
                {
                    b.HasOne("GymCrm.Domain.Messenger.ClientMessengerAccount", "Account")
                        .WithMany("Messages")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("MessengerMessages")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedMessengerMessages")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerReadState", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("MessengerReadStates")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "User")
                        .WithMany("ClientMessengerReadStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembership", b =>
                {
                    b.HasOne("GymCrm.Domain.Users.User", "ChangedByUser")
                        .WithMany("MembershipChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("Memberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "PaidByUser")
                        .WithMany("MembershipPayments")
                        .HasForeignKey("PaidByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymCrm.Domain.Clients.ClientMembershipSale", "Sale")
                        .WithMany("Memberships")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Client");

                    b.Navigation("PaidByUser");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembershipRefund", b =>
                {
                    b.HasOne("GymCrm.Domain.Users.User", "CanceledByUser")
                        .WithMany("CanceledMembershipRefunds")
                        .HasForeignKey("CanceledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("MembershipRefunds")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedMembershipRefunds")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Clients.ClientMembershipSale", "Sale")
                        .WithMany("Refunds")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanceledByUser");

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembershipSale", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("MembershipSales")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedMembershipSales")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.ClientGroup", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("Groups")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Groups.TrainingGroup", "Group")
                        .WithMany("Clients")
                        .HasForeignKey("GroupId", "BranchId")
                        .HasPrincipalKey("Id", "BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.ClientGroupAssignment", b =>
                {
                    b.HasOne("GymCrm.Domain.Clients.Client", "Client")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedClientGroupAssignments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Groups.TrainingGroup", "Group")
                        .WithMany("ClientAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.GroupTrainer", b =>
                {
                    b.HasOne("GymCrm.Domain.Groups.TrainingGroup", "Group")
                        .WithMany("Trainers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "Trainer")
                        .WithMany("AssignedGroups")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.GroupTrainerAssignment", b =>
                {
                    b.HasOne("GymCrm.Domain.Users.User", "CreatedByUser")
                        .WithMany("CreatedGroupTrainerAssignments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Groups.TrainingGroup", "Group")
                        .WithMany("TrainerAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Users.User", "Trainer")
                        .WithMany("GroupTrainerAssignments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Group");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.TrainingGroup", b =>
                {
                    b.HasOne("GymCrm.Domain.Branches.Branch", "Branch")
                        .WithMany("Groups")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Groups.GroupType", "GroupType")
                        .WithMany("Groups")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCrm.Domain.Branches.Hall", "Hall")
                        .WithMany("Groups")
                        .HasForeignKey("HallId", "BranchId")
                        .HasPrincipalKey("Id", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("GroupType");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("GymCrm.Domain.Branches.Branch", b =>
                {
                    b.Navigation("ClientAssignments");

                    b.Navigation("Clients");

                    b.Navigation("Groups");

                    b.Navigation("Halls");
                });

            modelBuilder.Entity("GymCrm.Domain.Branches.Hall", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.Client", b =>
                {
                    b.Navigation("AttendanceEntries");

                    b.Navigation("BranchAssignments");

                    b.Navigation("Contacts");

                    b.Navigation("GroupAssignments");

                    b.Navigation("Groups");

                    b.Navigation("MembershipRefunds");

                    b.Navigation("MembershipSales");

                    b.Navigation("Memberships");

                    b.Navigation("MessengerAccounts");

                    b.Navigation("MessengerLinkTokens");

                    b.Navigation("MessengerMessages");

                    b.Navigation("MessengerReadStates");
                });

            modelBuilder.Entity("GymCrm.Domain.Clients.ClientMembershipSale", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.GroupType", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("GymCrm.Domain.Messenger.ClientMessengerAccount", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("GymCrm.Domain.Groups.TrainingGroup", b =>
                {
                    b.Navigation("AttendanceEntries");

                    b.Navigation("ClientAssignments");

                    b.Navigation("Clients");

                    b.Navigation("TrainerAssignments");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("GymCrm.Domain.Users.User", b =>
                {
                    b.Navigation("AssignedGroups");

                    b.Navigation("AttendanceMarks");

                    b.Navigation("AuditLogs");

                    b.Navigation("CanceledMembershipRefunds");

                    b.Navigation("CreatedClientBranchAssignments");

                    b.Navigation("CreatedClientGroupAssignments");

                    b.Navigation("CreatedGroupTrainerAssignments");

                    b.Navigation("CreatedMembershipRefunds");

                    b.Navigation("CreatedMembershipSales");

                    b.Navigation("CreatedMessengerLinkTokens");

                    b.Navigation("CreatedMessengerMessages");

                    b.Navigation("GroupTrainerAssignments");

                    b.Navigation("ClientMessengerReadStates");

                    b.Navigation("MembershipChanges");

                    b.Navigation("MembershipPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
