using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GymCrm.UserFacingTextGuard;

public static partial class UserFacingTextScanner
{
    public static Task<ScanResult> ScanAsync(string repositoryRoot) => ScanAsync(
        Path.Combine(repositoryRoot, "backend/src"),
        Path.Combine(repositoryRoot, "scripts/harness/config/user-facing-text-inventory-index/scanner-exceptions.json"),
        Path.Combine(repositoryRoot, "scripts/harness/config/user-facing-text-allowlist.json"),
        repositoryRoot);

    public static async Task<ScanResult> ScanAsync(
        string sourceRoot,
        string exceptionsPath,
        string allowlistPath,
        string? repositoryRoot = null)
    {
        repositoryRoot ??= Directory.GetParent(Directory.GetParent(sourceRoot)!.FullName)!.FullName;
        var exceptions = await ReadExceptionEntriesAsync(exceptionsPath);
        var allowlist = await ReadEntriesAsync(allowlistPath);
        var acceptedExceptions = exceptions.Where(entry => entry.Path.StartsWith("backend/", StringComparison.Ordinal))
            .GroupBy(entry => EntryKey(entry.Path, entry.Fingerprint))
            .ToDictionary(group => group.Key, group => group.First());
        var acceptedAllowlist = allowlist.Where(entry => entry.Path.StartsWith("backend/", StringComparison.Ordinal))
            .ToDictionary(entry => EntryKey(entry.Path, entry.Fingerprint));
        var seenAllowlist = new HashSet<string>(StringComparer.Ordinal);
        var seenExceptions = new HashSet<string>(StringComparer.Ordinal);
        var violations = new List<Violation>();

        foreach (var file in Directory.EnumerateFiles(sourceRoot, "*.cs", SearchOption.AllDirectories).Order())
        {
            var normalized = file.Replace('\\', '/');
            if (normalized.Contains("/bin/") || normalized.Contains("/obj/")
                || normalized.Contains("/tests/") || normalized.Contains("/UserFacingText/")
                || normalized.EndsWith("Resources.cs", StringComparison.Ordinal)) continue;
            var source = await File.ReadAllTextAsync(file);
            if (source.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) continue;
            var tree = CSharpSyntaxTree.ParseText(source, path: file);
            var root = await tree.GetRootAsync();
            if (IsGeneratedPersistenceSource(root)) continue;
            foreach (var node in root.DescendantNodes().OfType<ExpressionSyntax>().Where(IsStringNode))
            {
                if (node.Ancestors().OfType<InterpolatedStringExpressionSyntax>().Any()) continue;
                var value = ValueOf(node);
                if (!CyrillicRegex().IsMatch(value)) continue;
                var path = Path.GetRelativePath(repositoryRoot, file).Replace('\\', '/');
                var fingerprint = Fingerprint(value);
                var key = EntryKey(path, fingerprint);
                if (acceptedExceptions.ContainsKey(key)) seenExceptions.Add(key);
                else if (acceptedAllowlist.ContainsKey(key)) seenAllowlist.Add(key);
                else if (!IsMachineContract(node, value) && !IsTelemetry(node))
                {
                    var line = tree.GetLineSpan(node.Span).StartLinePosition.Line + 1;
                    violations.Add(new(path, line, value, fingerprint));
                }
            }
        }

        var stale = acceptedAllowlist.Where(pair => !seenAllowlist.Contains(pair.Key)).Select(pair => pair.Value).ToArray();
        return new(violations, stale, seenExceptions.Count);
    }

    private static bool IsStringNode(ExpressionSyntax node) =>
        node is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.StringLiteralExpression)
        || node is InterpolatedStringExpressionSyntax;

    private static string ValueOf(ExpressionSyntax node) => node switch
    {
        LiteralExpressionSyntax literal => literal.Token.ValueText,
        InterpolatedStringExpressionSyntax interpolated => string.Concat(interpolated.Contents.Select(content => content switch
        {
            InterpolatedStringTextSyntax text => text.TextToken.ValueText,
            InterpolationSyntax interpolation => "{" + interpolation.Expression
                + interpolation.AlignmentClause?.ToString() + interpolation.FormatClause?.ToString() + "}",
            _ => string.Empty,
        })),
        _ => string.Empty,
    };

    private static bool IsMachineContract(ExpressionSyntax node, string value)
    {
        if (value.StartsWith('/')) return true;
        var assignment = node.AncestorsAndSelf().OfType<AssignmentExpressionSyntax>().FirstOrDefault();
        var declaration = node.AncestorsAndSelf().OfType<VariableDeclaratorSyntax>().FirstOrDefault();
        var name = (assignment?.Left.ToString() ?? declaration?.Identifier.ValueText ?? string.Empty).ToLowerInvariant();
        return new[] { "code", "route", "path", "callback", "command" }.Any(name.Contains);
    }

    private static bool IsTelemetry(ExpressionSyntax node)
    {
        var invocation = node.Ancestors().OfType<InvocationExpressionSyntax>().FirstOrDefault();
        if (invocation is null) return false;
        var target = invocation.Expression.ToString();
        return target.StartsWith("Console.", StringComparison.Ordinal)
            || target.Contains("Logger.", StringComparison.Ordinal)
            || target.Contains("Log", StringComparison.Ordinal);
    }

    private static bool IsGeneratedPersistenceSource(SyntaxNode root) =>
        root.DescendantNodes().OfType<ClassDeclarationSyntax>().Any(type =>
            type.BaseList?.Types.Any(baseType => baseType.Type.ToString() is "Migration" or "ModelSnapshot") == true);

    private static async Task<Entry[]> ReadExceptionEntriesAsync(string path)
    {
        var entries = (await ReadEntriesAsync(path)).ToList();
        if (!Path.GetFileName(path).Equals("scanner-exceptions.json", StringComparison.Ordinal)) return entries.ToArray();
        foreach (var shard in Directory.EnumerateFiles(Path.GetDirectoryName(path)!, "*.json"))
        {
            if (Path.GetFullPath(shard) == Path.GetFullPath(path)) continue;
            entries.AddRange(await ReadEntriesAsync(shard));
        }
        return entries.ToArray();
    }

    private static async Task<Entry[]> ReadEntriesAsync(string path)
    {
        await using var stream = File.OpenRead(path);
        using var document = await JsonDocument.ParseAsync(stream);
        return document.RootElement.GetProperty("entries").EnumerateArray().Select(item => new Entry(
            item.GetProperty("path").GetString()!, item.GetProperty("fingerprint").GetString()!)).ToArray();
    }

    private static string Fingerprint(string value) =>
        "sha256:" + Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(value)));

    private static string EntryKey(string path, string fingerprint) => $"{path}\0{fingerprint}";

    [GeneratedRegex("[А-Яа-яЁё]")]
    private static partial Regex CyrillicRegex();
}

public sealed record ScanResult(IReadOnlyList<Violation> Violations, IReadOnlyList<Entry> StaleAllowlist, int SeenExceptions);
public sealed record Violation(string Path, int Line, string Value, string Fingerprint);
public sealed record Entry(string Path, string Fingerprint);
