export const fe10SettingsBranchesShellText = {
  branchSettingsScreen_confirmLabel_d15a5f04: "Удалить зал",
  branchSettingsScreen_description_29f03982: "Создайте первый зал, чтобы группы могли ссылаться на место тренировок.",
  branchSettingsScreen_description_c4393b12: "После создания филиала можно будет добавить залы и использовать их в формах CRM.",
  branchSettingsScreen_jsxText_0d7606f3: "· Групп: ",
  branchSettingsScreen_jsxText_40c98d2e: "Филиал: ",
  branchSettingsScreen_jsxText_5189135a: "Повторить ",
  branchSettingsScreen_jsxText_59792556: "Редактировать ",
  branchSettingsScreen_jsxText_5ae41424: "Описание филиала пока не добавлено. ",
  branchSettingsScreen_jsxText_5ef59352: "Выберите филиал в списке. ",
  branchSettingsScreen_jsxText_6ea69b07: "· Клиентов: ",
  branchSettingsScreen_jsxText_7c47f729: "Отменить ",
  branchSettingsScreen_jsxText_a47c0b9b: "Зал выбирается в форме тренировочной группы. ",
  branchSettingsScreen_jsxText_a7076496: "Залы филиала",
  branchSettingsScreen_jsxText_b4d30cae: "Сохранить ",
  branchSettingsScreen_jsxText_c72164c0: "Групп: ",
  branchSettingsScreen_jsxText_f8d072c0: "Залов: ",
  branchSettingsScreen_jsxText_fd79d4d5: "Добавить зал ",
  branchSettingsScreen_label_13653782: "Название филиала",
  branchSettingsScreen_label_4a7c4927: "Добавить филиал",
  branchSettingsScreen_label_603e460b: "Обновить",
  branchSettingsScreen_label_7f077277: "Название зала",
  branchSettingsScreen_label_9b4fd5a5: "Загружаем филиалы и залы...",
  branchSettingsScreen_label_b3680f2c: "Описание",
  branchSettingsScreen_label_da82e805: "Адрес",
  branchSettingsScreen_message_204edcc3: (value0: unknown) => "Зал «" + String(value0) + "» удален из филиала.",
  branchSettingsScreen_message_6443763c: (value0: unknown) => "Филиал «" + String(value0) + "» сохранен.",
  branchSettingsScreen_message_9055dca1: (value0: unknown) => "Зал «" + String(value0) + "» сохранен.",
  branchSettingsScreen_message_cf9f9867: (value0: unknown) => "Зал «" + String(value0) + "» обновлен.",
  branchSettingsScreen_message_f9bc60e6: (value0: unknown) => "Филиал «" + String(value0) + "» обновлен.",
  branchSettingsScreen_placeholder_00fbfc3f: "Город, улица, дом",
  branchSettingsScreen_placeholder_4b0e7dac: "Например, Основной зал",
  branchSettingsScreen_placeholder_caae3b66: "Покрытие, вместимость или служебная заметка",
  branchSettingsScreen_placeholder_e61a6c67: "Например, Центр",
  branchSettingsScreen_placeholder_fcff79af: "Короткая заметка для администраторов",
  branchSettingsScreen_setActionError_860660d3: "Не удалось сохранить зал.",
  branchSettingsScreen_setActionError_edc2801e: "Не удалось сохранить филиал.",
  branchSettingsScreen_string_0143b43b: "Зал обновлен",
  branchSettingsScreen_string_0909dfc7: "Архивный",
  branchSettingsScreen_string_0cafa321: "Редактировать филиал",
  branchSettingsScreen_string_15106c19: "Описание не добавлено",
  branchSettingsScreen_string_1ca66519: "В архив",
  branchSettingsScreen_string_47862d95: "Филиал архивирован",
  branchSettingsScreen_string_4824b8e0: "Зал архивирован",
  branchSettingsScreen_string_4e52991b: "Удалить выбранный зал?",
  branchSettingsScreen_string_51f4db1b: "Адрес не указан",
  branchSettingsScreen_string_53340e79: "Новый филиал",
  branchSettingsScreen_string_58270ae4: "Новый зал",
  branchSettingsScreen_string_5ae0e885: "Вернуть",
  branchSettingsScreen_string_866cb8e4: "Не удалось изменить статус филиала.",
  branchSettingsScreen_string_a2ba13b7: "Не удалось удалить зал.",
  branchSettingsScreen_string_a3a972ea: "Филиал обновлен",
  branchSettingsScreen_string_b1511003: "Не удалось изменить статус зала.",
  branchSettingsScreen_string_b199b4ab: "Редактировать зал",
  branchSettingsScreen_string_b6a816b2: "Зал создан",
  branchSettingsScreen_string_bcb7882e: "Не удалось загрузить филиалы и залы.",
  branchSettingsScreen_string_be6881d5: "Активный",
  branchSettingsScreen_string_d77dfdcd: "Не выбран",
  branchSettingsScreen_string_da34740b: "Зал возвращен",
  branchSettingsScreen_string_e5873c80: "Филиал создан",
  branchSettingsScreen_string_fdb40bc2: "Филиал возвращен",
  branchSettingsScreen_template_1b633f97: (value0: unknown) => "Редактировать зал " + String(value0) + "",
  branchSettingsScreen_template_1cc27ebf: (value0: unknown) => "Архивировать зал " + String(value0) + "",
  branchSettingsScreen_template_47c56444: (value0: unknown) => "Открыть филиал " + String(value0) + "",
  branchSettingsScreen_template_723fe81a: (value0: unknown) => "Удалить зал " + String(value0) + "",
  branchSettingsScreen_template_978bfaa1: (value0: unknown) => "Backend не удалит зал «" + String(value0) + "», если он уже используется группами.",
  branchSettingsScreen_template_c34fa15a: (value0: unknown) => "Вернуть зал " + String(value0) + "",
  branchSettingsScreen_title_137fecae: "Удалить зал?",
  branchSettingsScreen_title_387e19a9: "Залы пока не созданы",
  branchSettingsScreen_title_3e453a66: "Филиалы и залы",
  branchSettingsScreen_title_4229f026: "Зал удален",
  branchSettingsScreen_title_7530f803: "Действие не выполнено",
  branchSettingsScreen_title_82d9adbb: "Филиалы пока не созданы",
  branchSettingsScreen_title_b1c39526: "Настройки не загрузились",
  settingsScreen_jsxText_0a3fd3c7: "Администраторы ",
  settingsScreen_jsxText_3e453a66: "Филиалы и залы ",
  settingsScreen_jsxText_59792556: "Редактировать ",
  settingsScreen_jsxText_7c47f729: "Отменить ",
  settingsScreen_jsxText_99c433e6: "Типы групп ",
  settingsScreen_jsxText_b2644036: "Абонементы ",
  settingsScreen_jsxText_b4d30cae: "Сохранить ",
  settingsScreen_jsxText_be99b136: "Удалить",
  settingsScreen_jsxText_c72164c0: "Групп: ",
  settingsScreen_label_0918b4ba: "Название",
  settingsScreen_label_81dcfe1a: "Загружаем типы групп...",
  settingsScreen_label_b3680f2c: "Описание",
  settingsScreen_label_ead26ac8: "Добавить тип",
  settingsScreen_message_7c4f3bca: (value0: unknown) => "Справочник «" + String(value0) + "» удален.",
  settingsScreen_message_eae6ee55: (value0: unknown) => "Справочник «" + String(value0) + "» сохранен.",
  settingsScreen_placeholder_00d135e4: "Краткое пояснение для администраторов",
  settingsScreen_placeholder_070fa4aa: "Например, Детская группа",
  settingsScreen_setFormError_a7a05224: "Не удалось сохранить тип группы.",
  settingsScreen_string_0b22e53e: "Тип группы обновлен",
  settingsScreen_string_2fea0015: "Введите название типа.",
  settingsScreen_string_33718ea5: "Тип группы создан",
  settingsScreen_string_3459cccc: "Новый тип группы",
  settingsScreen_string_418d8149: "Не удалось удалить тип группы.",
  settingsScreen_string_aa06a031: "Не удалось загрузить типы групп.",
  settingsScreen_string_ed4e0fd4: "Редактирование типа",
  settingsScreen_template_2dd95e54: (value0: unknown) => "Тип «" + String(value0) + "» будет удален из справочника.",
  settingsScreen_title_09e1875e: "Сохранение не выполнено",
  settingsScreen_title_534bb5ea: "Типы групп пока не заведены",
  settingsScreen_title_985b5e0f: "Настройки",
  settingsScreen_title_a040ef93: "Тип группы удален",
  settingsScreen_title_cf16993b: "Удаление не выполнено",
  settingsScreen_title_d81794ff: "Типы групп не загрузились",
  settingsScreen_title_f99a8a6f: "Удалить тип группы?",
} as const
