export const fe17SharedRoutingThemeText = {
  activeFiltersBar_ariaLabel_11c117e1: "Активные фильтры",
  activeFiltersBar_template_24308fe4: (value0: unknown) => "Удалить фильтр «" + String(value0) + "»",
  administrators_string_d8c07c44: "Группа без названия",
  appRoutes_attendance_5f43e5f1: "Посещения",
  appRoutes_attention_f17ceff0: "Внимание",
  appRoutes_audit_97c459a6: "Журнал",
  appRoutes_clients_ff296dda: "Клиенты",
  appRoutes_finance_d833b857: "Финансы",
  appRoutes_groups_cd8c5873: "Группы",
  appRoutes_label_1ae0c0dd: "Новый тренер",
  appRoutes_label_354d5f5b: "Смена пароля",
  appRoutes_label_3f7f75d8: "Редактирование группы",
  appRoutes_label_5a2595c2: "Новый клиент",
  appRoutes_label_6744d426: "Редактирование клиента",
  appRoutes_label_c9fd9fc0: "Новая группа",
  appRoutes_label_f303a273: "Редактирование тренера",
  appRoutes_schedule_92431022: "Расписание",
  appRoutes_settings_985b5e0f: "Настройки",
  appRoutes_users_0314946c: "Тренеры",
  attendance_requireRecord_050a21f7: "Некорректный ответ списка занятий на сегодня.",
  attendance_requireRecord_277c36ba: "Некорректный ответ списка групп посещений.",
  attendance_requireRecord_8f549520: "Некорректный ответ сохранения посещения.",
  attendance_requireRecord_91d6e39a: "Некорректный ответ состава группы.",
  attendance_string_0106f3ae: "Без имени",
  attendance_string_14d60c4c: "Ответ состава группы не содержит группу.",
  attendance_string_1592e0bf: "Ответ состава группы содержит некорректное состояние посещения.",
  attendance_string_4b13cbe8: "Ответ посещений не содержит календарную дату клуба.",
  attendance_string_6a2bab7f: "Ответ сохранения посещения содержит некорректную отметку.",
  attendance_string_8c0e01c1: "Ответ сохранения посещения не содержит группу.",
  attendance_string_9569db66: "Ответ сохранения посещения не содержит дату.",
  attendance_string_e0bd096d: "Ответ состава группы не содержит дату занятия.",
  audit_string_6da215b1: "Система",
  clients_string_0106f3ae: "Без имени",
  clients_string_1139430b: "Абонемент",
  clients_string_214235ce: "Без групп",
  clients_string_c1136d0e: " · отчётность",
  clients_string_c19bb335: "Планово",
  clients_string_d8c07c44: "Группа без названия",
  clients_template_6080f298: (value0: unknown, value1: unknown, value2: unknown) => "" + String(value0) + ". " + String(value1) + "" + String(value2) + "",
  componentRecipes_ariaLabel_bf427bdb: "Закрыть панель",
  componentRecipes_ariaLabel_db9cc7b2: "Закрыть окно",
  contrastMatrix_normalText_023c6df3: "destructive/hover",
  contrastMatrix_normalText_071d1ba1: "2/default",
  contrastMatrix_normalText_128e7ce7: "3/default",
  contrastMatrix_normalText_2259b12e: "filled/hover",
  contrastMatrix_normalText_2fbbe682: "default/default",
  contrastMatrix_normalText_324d5afa: "default/secondary",
  contrastMatrix_normalText_3a1b17be: "danger/default",
  contrastMatrix_normalText_3d8c9d63: "page/primary",
  contrastMatrix_normalText_4cbbfe12: "filled/default",
  contrastMatrix_normalText_58362b30: "card/secondary",
  contrastMatrix_normalText_5b0f2c6c: "card/primary",
  contrastMatrix_normalText_61291e9d: "selected/hover",
  contrastMatrix_normalText_849a1980: "page/secondary",
  contrastMatrix_normalText_8d8efcc1: "warning/default",
  contrastMatrix_normalText_9387e600: "filled/active",
  contrastMatrix_normalText_ac9ea1cc: "success/default",
  contrastMatrix_normalText_bd3d1bc9: "1/default",
  contrastMatrix_normalText_ce583282: "selected/default",
  contrastMatrix_normalText_d51608db: "info/default",
  contrastMatrix_normalText_db2889b5: "hover/default",
  contrastMatrix_normalText_dbe46d5f: "default/primary",
  contrastMatrix_normalText_dec346fe: "destructive/active",
  contrastMatrix_normalText_e368e4e5: "destructive/default",
  contrastMatrix_normalText_ec79291a: "4/default",
  contrastMatrix_normalText_ef3f9a38: "filled/disabled",
  endpoints_dEFAULTCLIENTGROUPNAME_d8c07c44: "Группа без названия",
  endpoints_dEFAULTFIELDERRORMESSAGE_8da2d9fc: "Проверьте значение поля.",
  endpoints_dEFAULTREQUESTERRORMESSAGE_747aa7a1: "Не удалось выполнить запрос.",
  entityLocatorBar_ariaLabel_428def6e: "Сбросить поисковый запрос",
  entityLocatorBar_jsxText_a69757b1: "Фильтры",
  entityLocatorBar_string_1d04cab7: "Открыть фильтры",
  entityLocatorBar_template_e78405ae: (value0: unknown) => "Открыть фильтры, активно " + String(value0) + "",
  groups_string_62ac1691: "Некорректный ответ списка групп.",
  groupSchedule_label_6fdf41c8: (value0: unknown, value1: unknown) => "" + String(value0) + ":" + String(value1) + "",
  groupSchedule_label_eaceb28c: (value0: unknown, value1: unknown) => "" + String(value0) + " · " + String(value1) + "",
  groupSchedule_string_0b7f45bb: "Зал не задан",
  groupSchedule_string_31a8ee2f: "Пн",
  groupSchedule_string_4ca114c2: "Пт",
  groupSchedule_string_7971972c: "Вс",
  groupSchedule_string_7ec16b9e: "Ср",
  groupSchedule_string_839b2d5c: "Вт",
  groupSchedule_string_8d62fb15: "Время не задано",
  groupSchedule_string_95661872: "Чт",
  groupSchedule_string_95dab017: "Сб",
  groupSchedule_string_97041ad9: "Длительность не задана",
  groupSchedule_string_e93b045d: "Тип не задан",
  groupSchedule_string_f783a57e: "Дни не заданы",
  groupSchedule_template_08b196b8: (value0: unknown) => "" + String(value0) + " мин",
  listRangeStatus_jsxText_d4f85d36: "–",
  listRangeStatus_string_81a306d7: "есть ещё",
  listRangeStatus_string_eaa048e3: "обновляем",
  listRangeStatus_template_911657b5: (value0: unknown) => "из " + String(value0) + "",
  mappers_string_0106f3ae: "Без имени",
  mobileBottomNavigation_ariaLabel_65356651: "Мобильная навигация",
  mobileBottomNavigation_ariaLabel_9b2568a1: "Остальные разделы ",
  mobileBottomNavigation_ariaLabel_da94ad10: "Ещё, открыть остальные разделы",
  mobileBottomNavigation_ariaLabel_f88e31a8: "Закрыть остальные разделы",
  mobileBottomNavigation_jsxText_2071fb99: "Ещё",
  navigationTabs_string_8fff0bba: "Основная навигация",
  semanticTones_label_0bf0fcb2: "Информация",
  semanticTones_label_34dc848e: "Требует внимания",
  semanticTones_label_4ad64e13: "Успешно",
  semanticTones_label_75a19e7a: "Нейтрально",
  semanticTones_label_f186cf19: "Критично",
  semanticVariables_authText_dcd6499f: "#171D27",
  semanticVariables_backgroundAlt_b4f56a75: "#EDF2EE",
  semanticVariables_crmAuthText_66927a9e: "--crm-auth-text",
  semanticVariables_crmSurfacePageAlt_06364c91: "--crm-surface-page-alt",
  semanticVariables_crmTextHeading_7593858d: "--crm-text-heading",
  semanticVariables_text_2a6f82d4: "#17312D",
  taskToolbarActions_string_603e460b: "Обновить",
  typography_crmFontFamilyHeading_36935063: "--crm-font-family-heading",
  typography_heading_adc69f43: "Onest, ui-sans-serif, system-ui, sans-serif",
  ux_ariaLabel_67723878: "Закрыть фильтры",
  ux_string_190c22c6: "Ещё фильтры",
  ux_string_1a9fb1f3: "Назад",
  ux_string_407f8717: "Сбросить",
  ux_string_648938b5: "Загружаем данные...",
  ux_string_a69757b1: "Фильтры",
  ux_string_ea58bb0b: "Дальше",
  ux_string_ef05d579: "Готово",
  ux_template_15ddf709: (value0: unknown) => "Страница " + String(value0) + ", текущая",
  ux_template_5cfba733: (value0: unknown) => "Страница " + String(value0) + "",
} as const
