export const fe15FinanceText = {
  financeReportPresentation_description_be8c12e8: "Измените период или снимите фильтры.",
  financeReportPresentation_jsxText_3ad52700: "Обновляем для ",
  financeReportPresentation_jsxText_d03502c4: ",",
  financeReportPresentation_jsxText_e7ac0786: ": ",
  financeReportPresentation_label_193f5e49: "Новые клиенты",
  financeReportPresentation_label_5189135a: "Повторить",
  financeReportPresentation_label_5a4cd443: "Продано абонементов",
  financeReportPresentation_label_6a187a49: "Выручка",
  financeReportPresentation_label_8f5cc749: "Загружаем финансовый отчет...",
  financeReportPresentation_label_976e03d3: "Повторить обновление",
  financeReportPresentation_label_e8fdd443: "Возвраты",
  financeReportPresentation_label_eed36406: "Чистая выручка",
  financeReportPresentation_month_c9086654: "Месяц",
  financeReportPresentation_quarter_2727c94f: "Квартал",
  financeReportPresentation_scopeText_f9ca0c09: (value0: unknown, value1: unknown) => "Филиал: " + String(value0) + " · Тренер: " + String(value1) + "",
  financeReportPresentation_string_7739db0f: "не задано",
  financeReportPresentation_string_e08bc1c8: "Запрос",
  financeReportPresentation_string_e6a83dba: "Отчет",
  financeReportPresentation_template_175bf575: (value0: unknown) => "Не удалось обновить отчет. Показаны ранее загруженные данные за " + String(value0) + ".",
  financeReportPresentation_template_a67459b7: (value0: unknown) => "Не удалось загрузить отчет для " + String(value0) + ",",
  financeReportPresentation_template_d4e70149: (value0: unknown) => "Показан предыдущий отчет: " + String(value0) + ",",
  financeReportPresentation_template_e68a10c0: (value0: unknown, value1: unknown) => "Филиал: " + String(value0) + ", Тренер: " + String(value1) + "",
  financeReportPresentation_template_edb2357a: (value0: unknown, value1: unknown) => "" + String(value0) + ", дата " + String(value1) + "",
  financeReportPresentation_title_20c61586: "За выбранный период операций нет.",
  financeReportPresentation_title_22598730: "Отчет не загрузился",
  financeReportPresentation_title_9687bd44: "Отчет не обновился",
  financeReportPresentation_year_d3b04324: "Год",
  financeReportScope_allLabel_0b471d0c: "Все тренеры",
  financeReportScope_allLabel_1b93eb9a: "Все филиалы",
  financeReportScope_fieldLabel_10e82072: "тренера",
  financeReportScope_fieldLabel_186f7067: "филиала",
  financeReportScope_message_c9d28435: (value0: unknown) => "Нельзя подтвердить scope финансового отчета: выбранный id " + String(value0) + " не найден в доступных backend списках.",
  financeReportsScreen_ariaLabel_bb6ea168: "Сбросить фильтры финансового отчета",
  financeReportsScreen_branchLabel_1b93eb9a: "Все филиалы",
  financeReportsScreen_duplicatedBreakdownHint_17d94038: "Итоги сверху считаются без дублей. В разбивке по группам и тренерам одна и та же продажа может попасть в несколько строк, если клиент был связан с несколькими группами или тренерами в выбранный период. Поэтому сумма строк в этих таблицах может быть больше итогов.",
  financeReportsScreen_emptyText_3b975c5b: "По филиалам нет строк за выбранный период.",
  financeReportsScreen_emptyText_77c767cb: "По тренерам нет строк за выбранный период.",
  financeReportsScreen_emptyText_f08244d4: "По группам нет строк за выбранный период.",
  financeReportsScreen_jsxText_407f8717: "Сбросить",
  financeReportsScreen_jsxText_46b59b71: "По филиалам",
  financeReportsScreen_jsxText_ece838e8: "По группам",
  financeReportsScreen_jsxText_fffad4a1: "По тренерам",
  financeReportsScreen_label_07b8c0e6: "С",
  financeReportsScreen_label_0d21a5dd: "Дата в периоде",
  financeReportsScreen_label_2727c94f: "Квартал",
  financeReportsScreen_label_2f17c4d2: "Филиал",
  financeReportsScreen_label_32d5a2ea: "Новые",
  financeReportsScreen_label_355eef19: "Продажи",
  financeReportsScreen_label_4885445c: "Быстрый период",
  financeReportsScreen_label_6a187a49: "Выручка",
  financeReportsScreen_label_894d7ecc: "Тренер",
  financeReportsScreen_label_907efbd4: "Группа",
  financeReportsScreen_label_a748e6aa: "Чистая",
  financeReportsScreen_label_b60ab9b4: "По",
  financeReportsScreen_label_c9086654: "Месяц",
  financeReportsScreen_label_d3b04324: "Год",
  financeReportsScreen_label_e8fdd443: "Возвраты",
  financeReportsScreen_label_e97ca72e: "Период",
  financeReportsScreen_message_8808f048: "Этот экран доступен только пользователям, которым backend выдал доступ к разделу финансов.",
  financeReportsScreen_string_0e92a776: "Не удалось загрузить финансовый отчет.",
  financeReportsScreen_string_74c10e83: "Не удалось загрузить списки фильтров.",
  financeReportsScreen_string_a69757b1: "Фильтры",
  financeReportsScreen_template_a545b6f5: (value0: unknown) => "Фильтры · " + String(value0) + "",
  financeReportsScreen_title_22162cc7: "Нельзя подтвердить scope финансового отчета",
  financeReportsScreen_title_2c77fd50: "Проверьте фильтры",
  financeReportsScreen_title_63c4a3fc: "Списки фильтров не загрузились",
  financeReportsScreen_title_662a562c: "Финансовые отчеты недоступны",
  financeReportsScreen_title_d833b857: "Финансы",
  financeReportsScreen_trainerLabel_0b471d0c: "Все тренеры",
} as const
