export const fe11SettingsUsersText = {
  administratorAttendanceScopeModal_ariaLabel_0df3659f: "Группы посещений администратора",
  administratorAttendanceScopeModal_detailsPush_48f11e95: (value0: unknown) => "Старт " + String(value0) + "",
  administratorAttendanceScopeModal_jsxText_2693c65e: "Недоступное сохраненное назначение",
  administratorAttendanceScopeModal_jsxText_40c98d2e: "Филиал: ",
  administratorAttendanceScopeModal_jsxText_4f049897: "Неактивна ",
  administratorAttendanceScopeModal_jsxText_5a3cdcb1: "ID группы: ",
  administratorAttendanceScopeModal_jsxText_6c99e7d8: "Вернуться ",
  administratorAttendanceScopeModal_jsxText_7725c76d: "Отозвать и сохранить ",
  administratorAttendanceScopeModal_jsxText_775fdb20: ". Доступ администратора к этим группам для посещений прекратится сразу после сохранения. ",
  administratorAttendanceScopeModal_jsxText_7c47f729: "Отменить ",
  administratorAttendanceScopeModal_jsxText_aa4fb6df: "Обновить данные ",
  administratorAttendanceScopeModal_jsxText_b4d30cae: "Сохранить ",
  administratorAttendanceScopeModal_jsxText_c9c7225b: "Выбрано: ",
  administratorAttendanceScopeModal_jsxText_d1e4b91d: "Будет отозван доступ к ",
  administratorAttendanceScopeModal_jsxText_dc6602c5: "Сохраняем изменения... ",
  administratorAttendanceScopeModal_jsxText_f3dd59ed: "К отзыву: ",
  administratorAttendanceScopeModal_label_b7466cdb: "Поиск группы",
  administratorAttendanceScopeModal_label_be99fd52: "Загружаем группы посещений...",
  administratorAttendanceScopeModal_placeholder_d45e66ab: "Название группы",
  administratorAttendanceScopeModal_setSaveError_d1a1bde7: "Не удалось сохранить группы посещений.",
  administratorAttendanceScopeModal_string_34482a84: "Расписание не указано",
  administratorAttendanceScopeModal_string_3ff106d7: "Группа отключена",
  administratorAttendanceScopeModal_string_46ad0080: "1 группе",
  administratorAttendanceScopeModal_string_7964adff: "Назначение недоступно.",
  administratorAttendanceScopeModal_string_863611e5: "Назначение больше не входит в допустимую область.",
  administratorAttendanceScopeModal_string_9c664ee0: "Филиал в архиве.",
  administratorAttendanceScopeModal_string_b921a80b: "не назначен",
  administratorAttendanceScopeModal_string_c37eb247: "Администратор отключен.",
  administratorAttendanceScopeModal_string_eb314df7: "Не удалось загрузить группы посещений.",
  administratorAttendanceScopeModal_template_9959259e: (value0: unknown) => "" + String(value0) + " группам",
  administratorAttendanceScopeModal_title_09e1875e: "Сохранение не выполнено",
  administratorAttendanceScopeModal_title_3bd7378e: "По совпадению ничего не найдено",
  administratorAttendanceScopeModal_title_76100b9d: "Отозвать доступ к группам?",
  administratorAttendanceScopeModal_title_8898e6fc: "В филиале нет групп для назначения",
  administratorAttendanceScopeModal_title_c50470cc: "Группы посещений",
  administratorAttendanceScopeModal_title_fc37228e: "Группы не загрузились",
  administratorsSettingsPanel_jsxText_1ec6f510: "Открыть филиалы и залы ",
  administratorsSettingsPanel_jsxText_40c98d2e: "Филиал: ",
  administratorsSettingsPanel_jsxText_5189135a: "Повторить ",
  administratorsSettingsPanel_jsxText_5336bb8f: "Открыть группы посещений ",
  administratorsSettingsPanel_jsxText_59792556: "Редактировать ",
  administratorsSettingsPanel_jsxText_65329f77: "Только просмотр ",
  administratorsSettingsPanel_jsxText_7c47f729: "Отменить ",
  administratorsSettingsPanel_jsxText_8541e28c: "Логин: ",
  administratorsSettingsPanel_jsxText_9f488310: "Доступ: все филиалы ",
  administratorsSettingsPanel_jsxText_a19c2c9d: "Telegram ID: ",
  administratorsSettingsPanel_jsxText_af8fd683: "Для администратора нужен активный филиал. Суперадминистратор сохраняется без филиала. ",
  administratorsSettingsPanel_jsxText_b4d30cae: "Сохранить ",
  administratorsSettingsPanel_jsxText_b934965b: "Нет активных филиалов ",
  administratorsSettingsPanel_jsxText_c1f3ef35: "Попросите главного тренера создать или восстановить филиал. ",
  administratorsSettingsPanel_jsxText_c50470cc: "Группы посещений ",
  administratorsSettingsPanel_label_3301ad7a: "Филиал администратора",
  administratorsSettingsPanel_label_6fbc47d4: "Загружаем администраторов...",
  administratorsSettingsPanel_label_d8506f3e: "Добавить администратора",
  administratorsSettingsPanel_message_00a3576f: (value0: unknown) => "Изменения «" + String(value0) + "» сохранены.",
  administratorsSettingsPanel_message_435c8ca7: "Администратор больше не доступен в этом разделе. Список обновляется.",
  administratorsSettingsPanel_message_4fb25546: (value0: unknown) => "Пользователь «" + String(value0) + "» добавлен.",
  administratorsSettingsPanel_setFormError_1cfc073d: "Не удалось сохранить администратора.",
  administratorsSettingsPanel_setFormError_7b41d62c: "Не удалось создать администратора.",
  administratorsSettingsPanel_string_0a14a43a: "Архивный филиал",
  administratorsSettingsPanel_string_13116bcf: "Загружаем филиалы...",
  administratorsSettingsPanel_string_14c70922: "Выберите филиал администратора.",
  administratorsSettingsPanel_string_22f2b253: "Редактирование администратора",
  administratorsSettingsPanel_string_4c5ee5d8: "Выберите филиал",
  administratorsSettingsPanel_string_7ff6dab6: "Редактирование суперадминистратора",
  administratorsSettingsPanel_string_9447dd32: "Введите ФИО администратора.",
  administratorsSettingsPanel_string_9a4fb41a: "Посещения: не назначены",
  administratorsSettingsPanel_string_a87a4b39: "Активен",
  administratorsSettingsPanel_string_ae1e2dac: "Введите стартовый пароль.",
  administratorsSettingsPanel_string_b7e3374d: "Администратор активен",
  administratorsSettingsPanel_string_b921a80b: "не назначен",
  administratorsSettingsPanel_string_c1351bd6: "Новый администратор",
  administratorsSettingsPanel_string_c62edde1: "Отключен",
  administratorsSettingsPanel_string_c9715294: "Введите логин.",
  administratorsSettingsPanel_string_d64134c2: "Не удалось загрузить администраторов.",
  administratorsSettingsPanel_string_d9ac9f77: "Суперадминистратор активен",
  administratorsSettingsPanel_string_e7040772: "Выберите роль.",
  administratorsSettingsPanel_string_eb5b2e75: "Не удалось загрузить филиалы.",
  administratorsSettingsPanel_template_2c46082c: (value0: unknown) => "" + String(value0) + " группы",
  administratorsSettingsPanel_template_67192921: (value0: unknown) => "" + String(value0) + " группа",
  administratorsSettingsPanel_template_8a059471: (value0: unknown) => "Посещения: " + String(value0) + "",
  administratorsSettingsPanel_template_8b720813: (value0: unknown) => "" + String(value0) + " групп",
  administratorsSettingsPanel_template_cc8da12a: (value0: unknown) => "" + String(value0) + " (архивный)",
  administratorsSettingsPanel_title_09e1875e: "Сохранение не выполнено",
  administratorsSettingsPanel_title_1f20f670: "Филиал обязателен",
  administratorsSettingsPanel_title_7ccf0bed: (value0: unknown) => "" + String(value0) + " обновлен",
  administratorsSettingsPanel_title_8bb025fe: "Запись изменилась",
  administratorsSettingsPanel_title_9d13455a: "Администраторы не загрузились",
  administratorsSettingsPanel_title_9d518c0f: "Филиалы не загрузились",
  administratorsSettingsPanel_title_baf4888f: (value0: unknown) => "" + String(value0) + " создан",
  administratorsSettingsPanel_title_f3d522b4: "Администраторы пока не добавлены",
  userEditScreen_jsxText_36d97fdf: "Backend не разрешил действия изменения для этой учетной записи. ",
  userEditScreen_label_aba60338: "Загружаем карточку тренера...",
  userEditScreen_title_ee98a5ee: "Карточка доступна только для просмотра",
  usersListScreen_ariaLabel_49234431: "Повторить загрузку списка тренеров",
  usersListScreen_ariaLabel_544fa84d: "Результаты поиска тренеров",
  usersListScreen_jsxText_407f8717: "Сбросить ",
  usersListScreen_jsxText_5189135a: "Повторить ",
  usersListScreen_jsxText_6e1f7baa: "Очистить поиск ",
  usersListScreen_jsxText_e7ac0786: ": ",
  usersListScreen_label_d85336e3: "Загружаем тренеров...",
  usersListScreen_template_1fa0371e: (value0: unknown) => "Редактировать тренера «" + String(value0) + "»",
  usersListScreen_title_0314946c: "Тренеры",
} as const
