export const fe12SettingsMembershipText = {
  membershipCatalogSettings_jsxText_4f8865ab: "• ",
  membershipCatalogSettings_jsxText_7c47f729: "Отменить",
  membershipCatalogSettings_jsxText_b4d30cae: "Сохранить",
  membershipCatalogSettings_jsxText_b8b151d4: "Изменить",
  membershipCatalogSettings_jsxText_bda05058: "— ",
  membershipCatalogSettings_label_0918b4ba: "Название",
  membershipCatalogSettings_label_132b8f43: "Поведение",
  membershipCatalogSettings_label_274b0f43: "Абонемент на срок",
  membershipCatalogSettings_label_2e4affe4: "Загружаем каталог...",
  membershipCatalogSettings_label_4a3c0cb7: "Доступен по",
  membershipCatalogSettings_label_6c90f338: "Филиал каталога",
  membershipCatalogSettings_label_9d2be902: "Доступен с",
  membershipCatalogSettings_label_a4dd0afc: "Разовое посещение",
  membershipCatalogSettings_label_be0e705c: "Цена",
  membershipCatalogSettings_label_cad58cd3: "Добавить абонемент",
  membershipCatalogSettings_string_018f2727: "Не удалось сохранить абонемент.",
  membershipCatalogSettings_string_029764c0: "Загружаем филиалы…",
  membershipCatalogSettings_string_271a3cca: "Нет доступного филиала",
  membershipCatalogSettings_string_2998ba4c: "Не удалось загрузить каталог.",
  membershipCatalogSettings_string_326a3ef9: "Цена должна быть больше нуля.",
  membershipCatalogSettings_string_61be650d: "Введите название.",
  membershipCatalogSettings_string_8cce07e6: "Редактирование абонемента",
  membershipCatalogSettings_string_9d518c0f: "Филиалы не загрузились",
  membershipCatalogSettings_string_a25d9d8a: "бессрочно",
  membershipCatalogSettings_string_a946d490: "Новый абонемент",
  membershipCatalogSettings_string_b284dfda: "Укажите дату начала.",
  membershipCatalogSettings_string_eb5b2e75: "Не удалось загрузить филиалы.",
  membershipCatalogSettings_template_415f4687: (value0: unknown) => "Редактировать " + String(value0) + "",
  membershipCatalogSettings_template_6c24496b: (value0: unknown) => "Действия каталога абонементов: " + String(value0) + "",
  membershipCatalogSettings_title_63cfba6d: "Не удалось загрузить филиалы",
  membershipCatalogSettings_title_af483cf5: "В этом филиале ещё нет абонементов",
  membershipCatalogSettings_title_db57eb5b: "Каталог не загрузился",
} as const
