export const fe16AuditText = {
  auditLogScreen_accessible_279b9ae5: (value0: unknown) => "ID объекта: " + String(value0) + "",
  auditLogScreen_ariaLabel_8f65a33f: "Закрыть подробности записи",
  auditLogScreen_ariaLabel_ac5dad76: "Журнал действий",
  auditLogScreen_date_732063f1: "Дата не указана",
  auditLogScreen_emptyLabel_745d0810: "Для этой записи новые значения не переданы.",
  auditLogScreen_emptyLabel_7ec59469: "Для этой записи старые значения не переданы.",
  auditLogScreen_jsxText_232a0ead: "Дата",
  auditLogScreen_jsxText_5189135a: "Повторить ",
  auditLogScreen_jsxText_773190d8: "Детали ",
  auditLogScreen_jsxText_7a4effe6: "ID объекта: ",
  auditLogScreen_jsxText_b3680f2c: "Описание",
  auditLogScreen_jsxText_cd45ec78: "Сбросить фильтры ",
  auditLogScreen_knownPrefix_6b53aafe: "Действие",
  auditLogScreen_knownPrefix_cedecb91: "Объект",
  auditLogScreen_label_0ce02910: (value0: unknown, value1: unknown) => "" + String(value0) + " (" + String(value1) + ")",
  auditLogScreen_label_141826fe: "Загружаем журнал действий...",
  auditLogScreen_label_1c084473: "Период по",
  auditLogScreen_label_273ec7a8: "Страницы журнала действий",
  auditLogScreen_label_2a5c42af: "Пользователь",
  auditLogScreen_label_56e46960: "Источник",
  auditLogScreen_label_6fd845da: "Тип действия",
  auditLogScreen_label_802e7822: "Тип объекта",
  auditLogScreen_label_8cfeb847: "Мессенджер",
  auditLogScreen_label_adf428d2: "Период с",
  auditLogScreen_message_9d346056: "Этот экран доступен главному тренеру и администратору.",
  auditLogScreen_placeholder_1627d7ae: "Все мессенджеры",
  auditLogScreen_placeholder_520f22d9: "Все объекты",
  auditLogScreen_placeholder_71e214e1: "Все источники",
  auditLogScreen_placeholder_ca80a4db: "Все действия",
  auditLogScreen_placeholder_f92b5e39: "Все пользователи",
  auditLogScreen_setStaleError_13cc8e2d: "Не удалось обновить, показаны предыдущие данные",
  auditLogScreen_string_045eef2d: "Первая страница журнала",
  auditLogScreen_string_1ab37d8d: "Под выбранные фильтры записей нет.",
  auditLogScreen_string_27e93106: "Сбросьте фильтры или обновите журнал после новых действий в системе.",
  auditLogScreen_string_3c961410: "Не удалось загрузить журнал действий.",
  auditLogScreen_string_3cedc553: "В журнале пока нет записей",
  auditLogScreen_string_65ab7b28: "Описание не передано",
  auditLogScreen_string_b2c30064: "Последняя страница журнала",
  auditLogScreen_string_d04b363e: "Следующая страница журнала",
  auditLogScreen_string_d0563fd0: "Обновите журнал после новых действий в системе.",
  auditLogScreen_string_f94be165: "Предыдущая страница журнала",
  auditLogScreen_template_41f458cd: (value0: unknown) => "Описание: " + String(value0) + "",
  auditLogScreen_template_4fbaec54: (value0: unknown) => "Страница " + String(value0) + " журнала",
  auditLogScreen_template_5456888e: (value0: unknown) => "Страница " + String(value0) + "",
  auditLogScreen_template_58747b6a: (value0: unknown, value1: unknown) => "Страница " + String(value0) + " из " + String(value1) + "",
  auditLogScreen_template_c1129cd4: (value0: unknown) => "Автор: " + String(value0) + "",
  auditLogScreen_template_f73af74a: (value0: unknown) => "Показать подробности записи: " + String(value0) + "",
  auditLogScreen_title_207b3102: "Данные могли устареть",
  auditLogScreen_title_509cc0db: "Журнал действий недоступен",
  auditLogScreen_title_900936e9: "Журнал не загрузился",
  auditLogScreen_title_97c459a6: "Журнал",
  auditLogScreen_title_a4383fdb: "Подробности записи журнала",
  auditLogScreen_title_b1ac9321: "Старые значения",
  auditLogScreen_title_e4283670: "Новые значения",
  auditLogScreen_unknownPrefix_597bec43: "Мессенджер из API",
  auditLogScreen_unknownPrefix_6ce2dabd: "Источник из API",
  auditLogScreen_unknownPrefix_6faaa941: "Тип действия из API",
  auditLogScreen_unknownPrefix_ee943359: "Тип объекта из API",
} as const
