export const fe1AppShellAuthText = {
  app_jsxText_10995e5b: "Проверьте подключение к сервису и повторите загрузку. ",
  app_jsxText_298e4132: "Повторить загрузку ",
  app_jsxText_2bf6591e: "Не удалось открыть экран входа",
  app_jsxText_9e550fe5: "Вход временно недоступен ",
  app_message_1cfdd5fd: (value0: unknown) => "Вы вышли из " + String(value0) + ".",
  app_message_1ffa77b1: (value0: unknown) => "Пароль обновлен. " + String(value0) + "",
  app_string_125fb9c9: "Попробуйте выполнить выход еще раз.",
  app_string_28e033b4: "Нет доступа",
  app_string_3ded90c0: "Пароль обновлен",
  app_string_44c2ac7c: "Первый вход завершен",
  app_string_8ad4d05f: "Новая сессия уже активна, можно продолжать работу.",
  app_string_ac621ca1: "Не удалось связаться с сервером.",
  app_string_af9d3306: "Страница не найдена",
  app_string_e9d1ffdc: "Изменение сохранено и применено к текущей сессии.",
  app_title_311bf7c1: "Сессия завершена",
  app_title_42260baf: "Сервис недоступен",
  app_title_619ea5c7: "Пароль обновлен, открыт доступный раздел",
  app_title_7d2f9bda: "Не удалось завершить сессию",
  app_title_8eefda54: "Открыт доступный раздел",
  authenticatedShell_jsxText_354d5f5b: "Смена пароля ",
  authenticatedShell_roleLabel_6c771997: "Администратор",
  authenticatedShell_roleLabel_6d711278: "Главный тренер",
  authenticatedShell_roleLabel_894d7ecc: "Тренер",
  authenticatedShell_roleLabel_ba0c95d4: "Суперадминистратор",
  authenticatedShell_string_29b1d990: "Завершаем сессию...",
  authenticatedShell_string_75cd24c3: "Выход",
  authenticatedShell_template_4d237756: (value0: unknown) => "Открыть профильное меню пользователя " + String(value0) + "",
  authStages_jsxText_1a9fb1f3: "Назад ",
  authStages_jsxText_389f991b: "Добро пожаловать! ",
  authStages_jsxText_4c52deff: ". Стартовый пароль: ",
  authStages_jsxText_6c1c312c: "Стартовые данные",
  authStages_jsxText_709f75be: "Первый запуск системы",
  authStages_jsxText_71f070e5: "Пароль обновится сразу",
  authStages_jsxText_74b94887: "Проверяем, есть ли активный вход, и готовим экран авторизации. ",
  authStages_jsxText_7814c992: "Используйте новый пароль при следующих входах. ",
  authStages_jsxText_8fc9ab2e: "Войти ",
  authStages_jsxText_a415bb3d: "Если логин первого пользователя не переопределен на сервере, используйте ",
  authStages_jsxText_cdb4ee2a: ". ",
  authStages_jsxText_ef797c81: "12345678",
  authStages_label_5be12bfe: "Логин",
  authStages_label_cb1a2074: "Пароль",
  authStages_label_d83e5a22: "Текущий пароль",
  authStages_label_f104cf99: "Новый пароль",
  authStages_label_fb22627c: "Повторите новый пароль",
  authStages_placeholder_468937a8: "Введите логин",
  authStages_placeholder_63cd6ea9: "Придумайте новый пароль",
  authStages_placeholder_b45783ad: "Введите текущий пароль",
  authStages_placeholder_f741291a: "Введите пароль",
  authStages_setFormError_5e80ed29: "Не удалось выполнить вход. Попробуйте еще раз.",
  authStages_setFormError_fbaf8203: "Не удалось сохранить новый пароль. Попробуйте еще раз.",
  authStages_string_24155137: "Введите пароль.",
  authStages_string_40402c8b: "Сменить пароль и продолжить",
  authStages_string_468abab8: "Обновите пароль, который будете использовать при следующих входах.",
  authStages_string_4a13b77b: "Сохранить новый пароль",
  authStages_string_55d5440a: "Введите новый пароль.",
  authStages_string_5e511732: "Введите текущий временный пароль и задайте новый для дальнейшей работы.",
  authStages_string_65289257: "Пароли должны совпадать.",
  authStages_string_8715c92b: "Смена пароля из профиля",
  authStages_string_8783d8ab: "Смените пароль",
  authStages_string_c9715294: "Введите логин.",
  authStages_string_d1843171: "Введите текущий пароль.",
  authStages_title_144a149c: (value0: unknown) => "Открываем " + String(value0) + "",
  authStages_title_36349dab: "Изменение не сохранено",
  authStages_title_e0d7dae9: "Вход не выполнен",
  configThemeBootstrap_jsxText_177a9363: "Готовим оформление и экран авторизации. ",
  configThemeBootstrap_jsxText_482341a5: "Открываем CRM",
  routeViewport_description_b66231cd: "Такой страницы нет или ссылка устарела.",
  routeViewport_jsxText_d1441734: "Экран будет подключен отдельным обновлением. ",
  routeViewport_jsxText_ea1f4082: "Открыть ",
  routeViewport_template_4bb78ad0: (value0: unknown) => "У вас нет доступа к операции «" + String(value0) + "».",
  routeViewport_template_c832959f: (value0: unknown) => "У вас нет доступа к разделу «" + String(value0) + "».",
  routeViewport_title_28e033b4: "Нет доступа",
  routeViewport_title_8b737d65: "Раздел пока недоступен",
  routeViewport_title_af9d3306: "Страница не найдена",
  routeViewport_title_cd7d7203: "Раздел",
  useAppReturnNavigation_string_bd4176c8: "К группе",
  useAppReturnNavigation_string_fc6d18f1: "К посещениям",
  useAppReturnNavigation_string_fde25c93: "К списку клиентов",
  useAppRoute_string_148e56cb: "Изменение занятия",
  useAppRoute_string_1ae0c0dd: "Новый тренер",
  useAppRoute_string_354d5f5b: "Смена пароля",
  useAppRoute_string_3f7f75d8: "Редактирование группы",
  useAppRoute_string_4196b8be: "Разовое занятие",
  useAppRoute_string_5008cfdc: "Краткая карточка клиента",
  useAppRoute_string_56995ff3: "Занятие",
  useAppRoute_string_5a2595c2: "Новый клиент",
  useAppRoute_string_5f43e5f1: "Посещения",
  useAppRoute_string_6744d426: "Редактирование клиента",
  useAppRoute_string_a912ec86: "Карточка клиента",
  useAppRoute_string_c0c26d68: "Перенос занятия",
  useAppRoute_string_c9fd9fc0: "Новая группа",
  useAppRoute_string_cd3e4306: "Изменение серии",
  useAppRoute_string_f303a273: "Редактирование тренера",
  useAppRoute_template_144a149c: (value0: unknown) => "Открываем " + String(value0) + "",
  useAppRoute_template_1ad27b00: (value0: unknown) => "Войти в " + String(value0) + "",
  useAppRoute_template_49c566c1: (value0: unknown) => "Раздел «" + String(value0) + "»",
  useAppRoute_template_4e209ac0: (value0: unknown, value1: unknown) => "" + String(value0) + " — нет доступа • " + String(value1) + "",
  useAppRoute_template_821c2666: (value0: unknown) => "Смена пароля • " + String(value0) + "",
  useAppRoute_template_94c1356c: (value0: unknown, value1: unknown) => "Больше нет доступа: " + String(value0) + ". Открыт доступный раздел «" + String(value1) + "».",
  useAppRoute_template_eae52a62: (value0: unknown) => "Вход недоступен • " + String(value0) + "",
  useAppRoute_template_eb919eb4: (value0: unknown) => "Смените пароль • " + String(value0) + "",
  useAppRoute_template_f613365a: (value0: unknown) => "Операция «" + String(value0) + "»",
  useAppRoute_template_ff77bda7: (value0: unknown) => "Страница не найдена • " + String(value0) + "",
} as const
