export const fe14GroupStaffingText = {
  groupTrainerAssignmentsSection_description_72d93054: "Постоянные тренеры меняются отдельным подтверждаемым действием. Основные данные группы сохраняются выше без расписания и списка тренеров.",
  groupTrainerAssignmentsSection_description_b5251bc5: "Добавьте хотя бы один период, затем получите предпросмотр влияния на занятия.",
  groupTrainerAssignmentsSection_gENERICASSIGNMENTERROR_b044e028: "Не удалось сохранить назначения тренеров.",
  groupTrainerAssignmentsSection_jsxText_0918d565: "Добавить период ",
  groupTrainerAssignmentsSection_jsxText_672a522d: "Затронуто занятий: ",
  groupTrainerAssignmentsSection_jsxText_857a90c1: "Получить предпросмотр ",
  groupTrainerAssignmentsSection_jsxText_8b3890f6: "Сохранить назначения ",
  groupTrainerAssignmentsSection_jsxText_a137f17a: "· ",
  groupTrainerAssignmentsSection_jsxText_a43d49ca: "Периодов: ",
  groupTrainerAssignmentsSection_jsxText_be99b136: "Удалить ",
  groupTrainerAssignmentsSection_jsxText_cdb4ee2a: ". ",
  groupTrainerAssignmentsSection_jsxText_e9be6ac7: "Предпросмотр изменений",
  groupTrainerAssignmentsSection_jsxText_f853b1ba: "Предупреждений нет.",
  groupTrainerAssignmentsSection_jsxText_fb7dfed4: "Подтверждение действует до ",
  groupTrainerAssignmentsSection_label_a0ff92dd: (value0: unknown, value1: unknown) => "" + String(value0) + " (" + String(value1) + ")",
  groupTrainerAssignmentsSection_message_7a7b41bd: "Постоянные периоды тренеров применены к группе.",
  groupTrainerAssignmentsSection_placeholder_3928a7cc: "Выберите тренера",
  groupTrainerAssignmentsSection_setFormError_8c90a577: "Сначала получите предпросмотр назначений.",
  groupTrainerAssignmentsSection_string_11da4ac5: "Выберите тренера.",
  groupTrainerAssignmentsSection_string_8858264c: "Укажите корректную дату окончания.",
  groupTrainerAssignmentsSection_string_a9adf0fb: "Дата окончания не может быть раньше начала.",
  groupTrainerAssignmentsSection_string_bd7d6747: "Проверьте поля назначений.",
  groupTrainerAssignmentsSection_string_eb4a0393: "Укажите корректную дату начала.",
  groupTrainerAssignmentsSection_string_eed7cd02: "Добавьте хотя бы один период назначения.",
  groupTrainerAssignmentsSection_template_07b8af35: (value0: unknown) => "Тренер периода " + String(value0) + "",
  groupTrainerAssignmentsSection_template_b016d5be: (value0: unknown) => "Окончание периода " + String(value0) + "",
  groupTrainerAssignmentsSection_template_bb0c93bf: (value0: unknown) => "Начало периода " + String(value0) + "",
  groupTrainerAssignmentsSection_title_6f2a21ca: "Постоянные назначения тренеров",
  groupTrainerAssignmentsSection_title_7530f803: "Действие не выполнено",
  groupTrainerAssignmentsSection_title_759d829a: "Назначения тренеров сохранены",
  groupTrainerAssignmentsSection_title_eb93958c: "Периоды тренеров не заданы",
  groupTrainerSubstitutionsSection_active_68505b6d: "Активно",
  groupTrainerSubstitutionsSection_ariaLabel_8c0dc67f: "Текущие и будущие замещения",
  groupTrainerSubstitutionsSection_ariaLabel_c3c5b156: "История временных замещений",
  groupTrainerSubstitutionsSection_cancelled_23a2a9bf: "Отменено",
  groupTrainerSubstitutionsSection_description_bfe9a56a: "Старые периодные замещения доступны только для просмотра. Изменение тренера для конкретного занятия появится отдельным действием в календаре.",
  groupTrainerSubstitutionsSection_description_fcc54bde: "Текущие и будущие временные назначения будут показаны здесь только для контроля старых данных.",
  groupTrainerSubstitutionsSection_expired_b459ff8f: "Завершено",
  groupTrainerSubstitutionsSection_jsxText_1417b779: "История ",
  groupTrainerSubstitutionsSection_jsxText_1a48f320: "Показано ",
  groupTrainerSubstitutionsSection_jsxText_34a89a26: "Повторить загрузку замещений ",
  groupTrainerSubstitutionsSection_jsxText_51ad1397: "по ",
  groupTrainerSubstitutionsSection_jsxText_5539f6e6: "Неактивный тренер ",
  groupTrainerSubstitutionsSection_jsxText_7ca077e4: "Текущие и будущие ",
  groupTrainerSubstitutionsSection_jsxText_7f4adf31: "из ",
  groupTrainerSubstitutionsSection_jsxText_8541e28c: "Логин: ",
  groupTrainerSubstitutionsSection_jsxText_993cc81f: "Создание, изменение и отмена периодных замещений отключены в календаре занятий. ",
  groupTrainerSubstitutionsSection_jsxText_a1f5d39a: "с ",
  groupTrainerSubstitutionsSection_jsxText_c6826c78: "Показать ещё ",
  groupTrainerSubstitutionsSection_jsxText_e072195b: "включительно ",
  groupTrainerSubstitutionsSection_label_10365fea: "Загружаем временные замещения...",
  groupTrainerSubstitutionsSection_string_0cb0e0e6: "Не удалось загрузить замещения.",
  groupTrainerSubstitutionsSection_string_2d015c26: "Показать историю замещений",
  groupTrainerSubstitutionsSection_string_e92898f1: "Не удалось загрузить историю замещений.",
  groupTrainerSubstitutionsSection_string_f3b6b22a: "Скрыть историю замещений",
  groupTrainerSubstitutionsSection_title_2e1514c4: "История не загрузилась",
  groupTrainerSubstitutionsSection_title_38aa0143: "Текущих и будущих замещений нет",
  groupTrainerSubstitutionsSection_title_3b8a3e5b: "Замещения не загрузились",
  groupTrainerSubstitutionsSection_title_4e2bc0cd: "Временные замещения",
  groupTrainerSubstitutionsSection_upcoming_c4c9abc1: "Запланировано",
} as const
