export const fe13GroupsCoreText = {
  groupClientRow_jsxText_353ad7d1: "Телефон: ",
  groupClientRow_jsxText_a912ec86: "Карточка клиента ",
  groupClientRow_template_a4942e1b: (value0: unknown) => "Открыть карточку клиента " + String(value0) + "",
  groupCreateScreen_jsxText_1faaa276: "Нажмите «Создать группу», чтобы выполнить атомарное создание группы и расписания. ",
  groupCreateScreen_jsxText_23985cf1: "Проверьте расписание перед созданием",
  groupCreateScreen_jsxText_322693c9: "К списку групп ",
  groupCreateScreen_jsxText_cdb4ee2a: ". ",
  groupCreateScreen_jsxText_d5ff0d22: "Группа будет создана вместе с начальной серией занятий. Подтвердить можно до ",
  groupCreateScreen_label_7c47f729: "Отменить",
  groupCreateScreen_label_d8c36ed2: "Подготавливаем форму группы...",
  groupCreateScreen_message_613f7cb9: (value0: unknown) => "Группа «" + String(value0) + "» уже доступна в списке.",
  groupCreateScreen_setFormError_ee875cc4: "Не удалось создать группу. Попробуйте еще раз.",
  groupCreateScreen_string_4371fe93: "окончания срока предпросмотра",
  groupCreateScreen_string_52af7b72: "Проверьте предупреждение перед подтверждением.",
  groupCreateScreen_string_663c5248: "Создать группу",
  groupCreateScreen_string_857a90c1: "Получить предпросмотр",
  groupCreateScreen_string_c6241417: "Не удалось проверить создание группы. Проверьте поля и попробуйте снова.",
  groupCreateScreen_string_c9bed940: "Не удалось загрузить список тренеров.",
  groupCreateScreen_title_1f78cfd7: "Группа создана",
  groupCreateScreen_title_bb243bf5: "Не удалось подготовить форму",
  groupCreateScreen_title_c9fd9fc0: "Новая группа",
  groupEditScreen_ariaLabel_08e8f4e9: "Отменить переход к карточке клиента",
  groupEditScreen_description_a64fe90a: "После этапов клиентской базы здесь будет виден фактический состав группы.",
  groupEditScreen_jsxText_322693c9: "К списку групп ",
  groupEditScreen_jsxText_735b1ef6: "Не сохранять ",
  groupEditScreen_jsxText_8fbe9b75: "Отмена ",
  groupEditScreen_jsxText_b4d30cae: "Сохранить ",
  groupEditScreen_jsxText_e4748b11: "Перед открытием карточки выберите, что сделать с текущими изменениями группы. ",
  groupEditScreen_jsxText_f8ba76ae: "Всего: ",
  groupEditScreen_label_03b534a0: "Загружаем группу...",
  groupEditScreen_message_cd1b9038: (value0: unknown) => "Изменения группы «" + String(value0) + "» сохранены.",
  groupEditScreen_setFormError_4200416e: "Не удалось сохранить изменения группы.",
  groupEditScreen_setFormError_e9c0fdee: "Проверьте обязательные поля группы.",
  groupEditScreen_string_6685ec5f: "Не удалось загрузить данные группы.",
  groupEditScreen_submitLabel_744cf2b2: "Сохранить изменения",
  groupEditScreen_template_3afee36c: (value0: unknown) => "Настройка группы «" + String(value0) + "»",
  groupEditScreen_title_2122d00c: "Сохранить изменения в группе?",
  groupEditScreen_title_3440e0c0: "Группа обновлена",
  groupEditScreen_title_48aff34a: "В группе пока нет клиентов",
  groupEditScreen_title_9728304a: "Экран редактирования не загрузился",
  groupEditScreen_title_c9c7719c: "Клиенты группы",
  groupForm_description_28716432: "Можно выбрать несколько активных тренеров. Временное замещение на период настраивается отдельно и не меняет этот список.",
  groupForm_label_0314946c: "Тренеры",
  groupForm_label_1635ad1f: "Время начала",
  groupForm_label_182f7c57: "Зал",
  groupForm_label_2a326071: "Длительность",
  groupForm_label_2f17c4d2: "Филиал",
  groupForm_label_3e2bef5c: "Начало расписания",
  groupForm_label_480102a9: "Дни",
  groupForm_label_54ca642f: "Группа активна",
  groupForm_label_86f463be: "Дни недели",
  groupForm_label_9fb9bbfa: "Основные тренеры группы",
  groupForm_label_a0ff92dd: (value0: unknown, value1: unknown) => "" + String(value0) + " (" + String(value1) + ")",
  groupForm_label_a642a677: "Тип группы",
  groupForm_label_d45e66ab: "Название группы",
  groupForm_label_d4a6795c: "Тип",
  groupForm_label_d8b0757a: "Старт",
  groupForm_label_da09e40b: "Окончание расписания",
  groupForm_partsPush_4ebaca56: "архивный",
  groupForm_placeholder_06e7e5cc: "Выберите тренеров",
  groupForm_placeholder_39fa9ec1: "60",
  groupForm_placeholder_4c5ee5d8: "Выберите филиал",
  groupForm_placeholder_522e39df: "Выберите тип группы",
  groupForm_placeholder_cf5d1124: "18:00",
  groupForm_placeholder_d9cf2b88: "Например, Юниоры 18:00",
  groupForm_string_74f8ad03: "Сначала выберите филиал",
  groupForm_string_86ad6462: "После сохранения тренеры увидят назначенную группу в своем рабочем списке.",
  groupForm_string_96ac21d7: "На этом экране сохраняются только название, филиал, тип и активность группы.",
  groupForm_string_d52c67f8: "Выберите зал",
  groupForm_string_d77dfdcd: "Не выбран",
  groupForm_suffix_84d5d93d: " мин",
  groupForm_title_09e1875e: "Сохранение не выполнено",
  groupFormMapping_string_6994b743: "Введите название группы.",
  groupFormMapping_string_9d3e66f4: "Выберите тип группы.",
  groupFormMapping_string_d730d41d: "Укажите время начала тренировки.",
  groupManagementConstants_gROUPSDEFAULTNAME_907efbd4: "Группа",
  groupsListScreen_accessibleLabel_ebbe1ead: "Поиск групп по названию",
  groupsListScreen_ariaLabel_82f96580: "Закрыть фильтры групп",
  groupsListScreen_jsxText_0314946c: "Тренеры",
  groupsListScreen_jsxText_26c38cb9: "Без тренера: ",
  groupsListScreen_jsxText_407f8717: "Сбросить ",
  groupsListScreen_jsxText_5189135a: "Повторить ",
  groupsListScreen_jsxText_59792556: "Редактировать",
  groupsListScreen_jsxText_6e1f7baa: "Очистить поиск ",
  groupsListScreen_jsxText_907efbd4: "Группа",
  groupsListScreen_jsxText_92431022: "Расписание",
  groupsListScreen_jsxText_a137f17a: "· ",
  groupsListScreen_jsxText_bae09e03: "Список групп",
  groupsListScreen_jsxText_ef05d579: "Готово ",
  groupsListScreen_jsxText_f7642da6: "Филиал и зал",
  groupsListScreen_jsxText_f8ba76ae: "Всего: ",
  groupsListScreen_label_0cf113c5: "Загружаем список групп...",
  groupsListScreen_label_215816bf: "Все",
  groupsListScreen_label_225077c6: "Статус",
  groupsListScreen_label_2e31d9a4: "Страницы списка групп",
  groupsListScreen_label_3a3cdea7: (value0: unknown) => "Поиск: " + String(value0) + "",
  groupsListScreen_label_4b6feb75: "Неактивные",
  groupsListScreen_label_732e659e: "Без тренера",
  groupsListScreen_label_afde8d3f: "Обновить список групп",
  groupsListScreen_label_c9fd9fc0: "Новая группа",
  groupsListScreen_label_eeaeb976: "Активные",
  groupsListScreen_placeholder_d45e66ab: "Название группы",
  groupsListScreen_resetLabel_51d41686: "Сбросить все ",
  groupsListScreen_string_33e84aeb: "Группы пока не созданы",
  groupsListScreen_string_401b50ae: "Измените поисковый запрос или фильтры, чтобы расширить список.",
  groupsListScreen_string_4a9db5ba: "Активных групп без тренера: обновляем",
  groupsListScreen_string_69da2f93: "Создайте первую группу, чтобы закрепить тренеров и подготовить основу для сценария посещений.",
  groupsListScreen_string_85b97c29: "Не удалось загрузить список групп.",
  groupsListScreen_string_a674b477: "Тренер не назначен",
  groupsListScreen_string_e2d00d68: "Всего групп: обновляем",
  groupsListScreen_string_ed2efb2d: "Группы не найдены",
  groupsListScreen_template_0405138b: (value0: unknown) => "Всего групп: " + String(value0) + "",
  groupsListScreen_template_314bfdaa: (value0: unknown) => "Всего групп: " + String(value0) + "",
  groupsListScreen_template_5d140dac: (value0: unknown) => "Редактировать группу «" + String(value0) + "»",
  groupsListScreen_template_f84f017b: (value0: unknown) => "Активных групп без тренера: " + String(value0) + "",
  groupsListScreen_title_214164fa: "Список групп не загрузился",
  groupsListScreen_title_3fdee84e: "Обновление списка не загрузилось",
  groupsListScreen_title_7514e29a: "Фильтры групп",
  groupsListScreen_title_cd8c5873: "Группы",
  useGroupsListState_string_85b97c29: "Не удалось загрузить список групп.",
} as const
