export const fe2ScheduleCoreText = {
  groupScheduleScreen_accessibleContext_fc66225b: (value0: unknown, value1: unknown) => "" + String(value0) + ", " + String(value1) + "",
  groupScheduleScreen_accessibleName_0c4c88a4: (value0: unknown) => "Изменить занятие: " + String(value0) + "",
  groupScheduleScreen_ariaLabel_1be1fa3b: "Расписание занятий",
  groupScheduleScreen_ariaLabel_5c290213: "Дата расписания",
  groupScheduleScreen_ariaLabel_a6a7cac1: "Область изменения серии",
  groupScheduleScreen_ariaLabel_b645736b: "Загружаем занятия",
  groupScheduleScreen_ariaLabel_ce0f52ac: "Создать разовое занятие",
  groupScheduleScreen_ariaLabel_d9fc5a1d: "Вид календаря",
  groupScheduleScreen_confirm_1fad63df: "Назначить замену",
  groupScheduleScreen_description_222a0bea: "Занятия появятся после создания расписания или разового занятия.",
  groupScheduleScreen_description_8fd05e01: "Когда сервер даст доступ к вашим занятиям или заменам, они появятся здесь.",
  groupScheduleScreen_description_e328b6b5: "Сбросьте часть фильтров, чтобы снова увидеть занятия.",
  groupScheduleScreen_jsxText_05b83392: "Проверьте замену перед подтверждением",
  groupScheduleScreen_jsxText_0d7d0a5f: "Отметки есть",
  groupScheduleScreen_jsxText_23a2a9bf: "Отменено",
  groupScheduleScreen_jsxText_25d150a9: "В серии должен быть хотя бы один слот. Добавьте слот, чтобы сохранить расписание. ",
  groupScheduleScreen_jsxText_333afd46: "Удалить слот ",
  groupScheduleScreen_jsxText_38aaedce: "Слоты серии",
  groupScheduleScreen_jsxText_3fbb07c9: "В серии должен остаться хотя бы один слот. ",
  groupScheduleScreen_jsxText_4b5f3a17: "Серия с ",
  groupScheduleScreen_jsxText_4c414dbf: "Пропущено",
  groupScheduleScreen_jsxText_4e848f28: "Примеры занятий",
  groupScheduleScreen_jsxText_5189135a: "Повторить",
  groupScheduleScreen_jsxText_603e460b: "Обновить ",
  groupScheduleScreen_jsxText_61b682d8: "В этот день занятий нет",
  groupScheduleScreen_jsxText_61f9839e: "Добавить слот ",
  groupScheduleScreen_jsxText_672a522d: "Затронуто занятий: ",
  groupScheduleScreen_jsxText_720752c6: "Область: ",
  groupScheduleScreen_jsxText_758cc605: "Перенести ",
  groupScheduleScreen_jsxText_76f55a98: "Восстановить ",
  groupScheduleScreen_jsxText_7c47f729: "Отменить ",
  groupScheduleScreen_jsxText_8e72e5a3: "Подтвердить изменение серии ",
  groupScheduleScreen_jsxText_8fbe9b75: "Отмена ",
  groupScheduleScreen_jsxText_901e768a: ". Подтвердить можно до ",
  groupScheduleScreen_jsxText_9a72d56b: "Посещаемость ",
  groupScheduleScreen_jsxText_9b431254: "Вернуться к расписанию",
  groupScheduleScreen_jsxText_9b994009: "Замена ",
  groupScheduleScreen_jsxText_a137f17a: "· ",
  groupScheduleScreen_jsxText_a1f5d39a: "с ",
  groupScheduleScreen_jsxText_a69757b1: "Фильтры ",
  groupScheduleScreen_jsxText_a7bdff84: "Серия ",
  groupScheduleScreen_jsxText_ab7a9be4: "Снять замену",
  groupScheduleScreen_jsxText_b688b4c0: "Сегодня ",
  groupScheduleScreen_jsxText_b8b151d4: "Изменить ",
  groupScheduleScreen_jsxText_bd4bec1c: "Данные могут быть устаревшими ",
  groupScheduleScreen_jsxText_cce698e3: "Подтвердить можно до ",
  groupScheduleScreen_jsxText_cd45ec78: "Сбросить фильтры ",
  groupScheduleScreen_jsxText_cdb4ee2a: ". ",
  groupScheduleScreen_jsxText_d66006ce: "Проверьте изменение серии",
  groupScheduleScreen_jsxText_e2be3497: "Создать ",
  groupScheduleScreen_jsxText_ef05d579: "Готово",
  groupScheduleScreen_label_0c96696a: (value0: unknown, value1: unknown) => "" + String(value0) + "" + String(value1) + "",
  groupScheduleScreen_label_12be87c8: "Четверг",
  groupScheduleScreen_label_1635ad1f: "Время начала",
  groupScheduleScreen_label_182f7c57: "Зал",
  groupScheduleScreen_label_19aac587: "Кто проведёт занятие",
  groupScheduleScreen_label_2f17c4d2: "Филиал",
  groupScheduleScreen_label_442e7ad5: "Причина",
  groupScheduleScreen_label_45868810: "Загружаем параметры занятия...",
  groupScheduleScreen_label_5db04205: "Активная замена",
  groupScheduleScreen_label_63ad4f82: "День",
  groupScheduleScreen_label_68c27d77: "День недели",
  groupScheduleScreen_label_6ac938c0: "Дата окончания серии",
  groupScheduleScreen_label_82cba72b: "Загружаем серию занятий...",
  groupScheduleScreen_label_86301601: "Длительность, минут",
  groupScheduleScreen_label_8809248a: "Кого заменить",
  groupScheduleScreen_label_894d7ecc: "Тренер",
  groupScheduleScreen_label_907efbd4: "Группа",
  groupScheduleScreen_label_a2706736: "Вся серия",
  groupScheduleScreen_label_a59b45a7: "Понедельник",
  groupScheduleScreen_label_a642a677: "Тип группы",
  groupScheduleScreen_label_abbd2e86: "Пятница",
  groupScheduleScreen_label_b8a6c0dc: "Дата начала изменения",
  groupScheduleScreen_label_cdfa593d: "Вторник",
  groupScheduleScreen_label_d606a9df: "Среда",
  groupScheduleScreen_label_ddb0ee8e: "Суббота",
  groupScheduleScreen_label_eafa287c: "С этого дня",
  groupScheduleScreen_label_ef0c9403: "Загружаем занятие...",
  groupScheduleScreen_label_f4276ba4: "Воскресенье",
  groupScheduleScreen_label_ff2e564d: "Неделя",
  groupScheduleScreen_message_0fe8ae69: "Сервер не разрешил создание разового занятия для текущего пользователя.",
  groupScheduleScreen_placeholder_53042571: "Выберите замену",
  groupScheduleScreen_placeholder_5f1f1111: "Выберите тренера на замену",
  groupScheduleScreen_placeholder_d014731e: "Выберите постоянного тренера",
  groupScheduleScreen_string_055792ee: "Не удалось проверить серию занятий. Проверьте поля и попробуйте снова.",
  groupScheduleScreen_string_10e82072: "тренера",
  groupScheduleScreen_string_148e56cb: "Изменение занятия",
  groupScheduleScreen_string_1b31d0c9: "Не удалось загрузить серию занятий.",
  groupScheduleScreen_string_1d51e161: "Параметры календаря",
  groupScheduleScreen_string_274aa551: "Регулярное",
  groupScheduleScreen_string_2bb606b0: "Предыдущий день",
  groupScheduleScreen_string_301ca990: "Разовое",
  groupScheduleScreen_string_314ea9f7: "Не удалось загрузить занятие.",
  groupScheduleScreen_string_3e7f6ab3: "Не удалось проверить замену тренера. Проверьте поля и попробуйте снова.",
  groupScheduleScreen_string_404398f9: "1 занятие",
  groupScheduleScreen_string_4371fe93: "окончания срока предпросмотра",
  groupScheduleScreen_string_4edf0ecf: "Расписание не загрузилось",
  groupScheduleScreen_string_5ad6c3a3: "Следующий день",
  groupScheduleScreen_string_62b92aa4: "Обновить предпросмотр",
  groupScheduleScreen_string_648188fd: "вся серия",
  groupScheduleScreen_string_7ee7c6c8: "Не удалось обновить расписание",
  groupScheduleScreen_string_857a90c1: "Получить предпросмотр",
  groupScheduleScreen_string_904286db: "Следующая неделя",
  groupScheduleScreen_string_9d63ad76: "с этого дня",
  groupScheduleScreen_string_a674b477: "Тренер не назначен",
  groupScheduleScreen_string_ad9d22f9: "Сервер не разрешил это изменение занятия.",
  groupScheduleScreen_string_b1bdd1a5: "Изменение недоступно",
  groupScheduleScreen_string_bdc4bb60: "Предыдущая неделя",
  groupScheduleScreen_string_c0c26d68: "Перенос занятия",
  groupScheduleScreen_string_c8822d97: "Не удалось загрузить расписание.",
  groupScheduleScreen_string_cc2b2849: "Перенос недоступен",
  groupScheduleScreen_string_d2da32db: "Занятие не может быть изменено в составе этой операции.",
  groupScheduleScreen_string_d993628b: "Не удалось загрузить параметры занятия.",
  groupScheduleScreen_string_ffa4f44c: "Без отметок",
  groupScheduleScreen_template_23948761: (value0: unknown) => "" + String(value0) + " · замена",
  groupScheduleScreen_template_5aec8f4b: (value0: unknown) => "Открыть занятие: " + String(value0) + "",
  groupScheduleScreen_template_705c7b4e: (value0: unknown) => " · источник " + String(value0) + "",
  groupScheduleScreen_template_73ed7940: (value0: unknown) => "" + String(value0) + " занятий",
  groupScheduleScreen_template_855e5a61: (value0: unknown) => " по " + String(value0) + "",
  groupScheduleScreen_template_99ecdb89: (value0: unknown) => "Параметры календаря, активных фильтров: " + String(value0) + "",
  groupScheduleScreen_template_aea1f902: (value0: unknown) => " по " + String(value0) + "",
  groupScheduleScreen_template_ee5718b6: (value0: unknown) => " вместо " + String(value0) + "",
  groupScheduleScreen_template_f806750d: (value0: unknown) => "" + String(value0) + " занятия",
  groupScheduleScreen_title_1a4e8dc8: "Замена тренера",
  groupScheduleScreen_title_37c25119: "Снять замену тренера",
  groupScheduleScreen_title_3ea07537: "Параметры не загрузились",
  groupScheduleScreen_title_4196b8be: "Разовое занятие",
  groupScheduleScreen_title_53c1cb1e: "Для вас занятий нет",
  groupScheduleScreen_title_56995ff3: "Занятие",
  groupScheduleScreen_title_87f0bc93: "По выбранным фильтрам занятий нет",
  groupScheduleScreen_title_8c75c82d: "Расписание пока пустое",
  groupScheduleScreen_title_92431022: "Расписание",
  groupScheduleScreen_title_c2de061e: "Занятие не загрузилось",
  groupScheduleScreen_title_cd3e4306: "Изменение серии",
  groupScheduleScreen_title_d17d52ca: "Создание недоступно",
  groupScheduleScreen_title_f1cab840: "Серия не загрузилась",
  groupScheduleScreen_windowConfirm_9ca4aaac: "Отменить изменение серии и потерять черновик?",
  groupScheduleScreen_windowConfirm_f4d4ec01: "Отменить действие с заменой и потерять черновик?",
  scheduleActionReasons_attendanceForbidden_a90255c9: "Посещаемость недоступна для вашей роли или зоны доступа.",
  scheduleActionReasons_futureLesson_a00df924: "Посещаемость станет доступна в разрешённый период отметок.",
  scheduleActionReasons_groupTrainerAssignmentOverlap_96c9bf50: "У тренера есть пересекающееся постоянное назначение в другой группе.",
  scheduleActionReasons_lessonAttendanceStateConflict_811c0c2e: "У занятия уже есть отметки посещаемости.",
  scheduleActionReasons_lessonCancelled_558a4a9c: "Занятие отменено.",
  scheduleActionReasons_lessonHallOverlap_b7d37a1e: "В выбранное время в зале есть другое занятие.",
  scheduleActionReasons_lessonMutationPreviewExpired_d57c7823: "Время подтверждения истекло. Получите новый предпросмотр.",
  scheduleActionReasons_lessonMutationPreviewInvalid_ffd3593c: "Предпросмотр больше не действует. Получите новый предпросмотр.",
  scheduleActionReasons_lessonMutationPreviewStale_4558ad4e: "Параметры изменились после предпросмотра. Получите новый предпросмотр.",
  scheduleActionReasons_lessonNotCancelled_ff754a71: "Занятие не отменено.",
  scheduleActionReasons_lessonNotScheduled_14a746f8: "Занятие сейчас не запланировано.",
  scheduleActionReasons_lessonTrainerOverlap_a0dfe4d6: "В выбранное время у тренера есть другое занятие.",
  scheduleActionReasons_noSubstitution_1ec89fcc: "Для занятия нет активной замены тренера.",
  scheduleActionReasons_notImplemented_366e9d65: "Действие пока недоступно.",
  scheduleActionReasons_roleNotAllowed_ee8482c5: "Создание разового занятия недоступно для вашей роли.",
  scheduleActionReasons_scheduleMutationsUnavailable_bd3a9985: "Изменение расписания сейчас недоступно.",
  scheduleActionReasons_string_6f1c3a2e: "Действие сейчас недоступно.",
  schedulePresentation_string_3728896b: "участник",
  schedulePresentation_string_5f915be7: "занятия",
  schedulePresentation_string_8ed71a94: "занятие",
  schedulePresentation_string_ba6c01b2: "занятий",
  schedulePresentation_string_cebd852c: "участника",
  schedulePresentation_word_e3c8a505: "участников",
} as const
