export const fe3ScheduleMutationsText = {
  scheduleDeferredActions_accessibleName_1e00c5ab: (value0: unknown, value1: unknown) => "Перенести занятие: " + String(value0) + ", " + String(value1) + "",
  scheduleDeferredActions_accessibleName_39549900: (value0: unknown, value1: unknown) => "Восстановить занятие: " + String(value0) + ", " + String(value1) + "",
  scheduleDeferredActions_accessibleName_990472d3: (value0: unknown) => "Изменить серию занятий: " + String(value0) + "",
  scheduleDeferredActions_accessibleName_9c8f53cb: (value0: unknown, value1: unknown) => "Отменить занятие: " + String(value0) + ", " + String(value1) + "",
  scheduleDeferredActions_accessibleName_9e998c3e: (value0: unknown, value1: unknown) => "Назначить замену тренера: " + String(value0) + ", " + String(value1) + "",
  scheduleDeferredActions_accessibleName_af6692f4: (value0: unknown, value1: unknown) => "Снять замену тренера: " + String(value0) + ", " + String(value1) + "",
  scheduleDeferredActions_label_758cc605: "Перенести",
  scheduleDeferredActions_label_76f55a98: "Восстановить",
  scheduleDeferredActions_label_7c47f729: "Отменить",
  scheduleDeferredActions_label_9b994009: "Замена",
  scheduleDeferredActions_label_a7bdff84: "Серия",
  scheduleDeferredActions_label_ab7a9be4: "Снять замену",
  scheduleEventsDisclosure_ariaLabel_15189e3f: "Закрыть детали занятий",
  scheduleEventsDisclosure_jsxText_65b19bb3: "Занятия в интервале ",
  scheduleEventsDisclosure_jsxText_a137f17a: "· ",
  scheduleEventsDisclosure_jsxText_a318c242: "+",
  scheduleEventsDisclosure_string_4f049897: "Неактивна ",
  scheduleEventsDisclosure_string_89ce76b3: "Открыть детали",
  scheduleEventsDisclosure_string_a674b477: "Тренер не назначен",
  scheduleEventsDisclosure_string_e93b045d: "Тип не задан",
  scheduleEventsDisclosure_template_4c5bfbe1: (value0: unknown) => "" + String(value0) + " в интервале.",
  scheduleLessonCancellationDrawer_confirmLabel_563bed0c: "Отменить занятие",
  scheduleLessonCancellationDrawer_confirmLabel_b7179b95: "Восстановить занятие",
  scheduleLessonCancellationDrawer_description_06aebb09: "Занятие снова появится как запланированное. Проверьте точное занятие перед подтверждением.",
  scheduleLessonCancellationDrawer_description_c3c2aa40: "Отменяется только это занятие. Если уже есть отметки посещаемости, сервер попросит сначала разобрать отметки.",
  scheduleLessonCancellationDrawer_gENERICCANCELLATIONERROR_d585b2a5: "Не удалось проверить действие с занятием. Обновите предпросмотр и попробуйте снова.",
  scheduleLessonCancellationDrawer_jsxText_0d7d0a5f: "Отметки есть",
  scheduleLessonCancellationDrawer_jsxText_756d6c50: "Проверьте действие перед подтверждением",
  scheduleLessonCancellationDrawer_jsxText_8b575c5b: "После подтверждения: ",
  scheduleLessonCancellationDrawer_jsxText_8fbe9b75: "Отмена ",
  scheduleLessonCancellationDrawer_jsxText_a137f17a: "· ",
  scheduleLessonCancellationDrawer_jsxText_cce698e3: "Подтвердить можно до ",
  scheduleLessonCancellationDrawer_jsxText_cdb4ee2a: ". ",
  scheduleLessonCancellationDrawer_string_23a2a9bf: "Отменено",
  scheduleLessonCancellationDrawer_string_2d57c90a: "занятие восстановлено",
  scheduleLessonCancellationDrawer_string_4371fe93: "окончания срока предпросмотра",
  scheduleLessonCancellationDrawer_string_62b92aa4: "Обновить предпросмотр",
  scheduleLessonCancellationDrawer_string_857a90c1: "Получить предпросмотр",
  scheduleLessonCancellationDrawer_string_c4c9abc1: "Запланировано",
  scheduleLessonCancellationDrawer_string_f6756db0: "занятие отменено",
  scheduleLessonChangeDrawer_ariaLabel_594acbf8: "Область изменения расписания",
  scheduleLessonChangeDrawer_jsxText_247c84d3: "Изменение применяется с ",
  scheduleLessonChangeDrawer_jsxText_2aa98ec1: "Сейчас: ",
  scheduleLessonChangeDrawer_jsxText_3c2e873d: "Сохранить изменение ",
  scheduleLessonChangeDrawer_jsxText_6cce5c5e: "Проверьте изменение перед сохранением",
  scheduleLessonChangeDrawer_jsxText_720752c6: "Область: ",
  scheduleLessonChangeDrawer_jsxText_8fbe9b75: "Отмена ",
  scheduleLessonChangeDrawer_jsxText_a137f17a: "· ",
  scheduleLessonChangeDrawer_jsxText_bda05058: "— ",
  scheduleLessonChangeDrawer_jsxText_c26ffc1f: "Изменяются параметры серии занятий. Поля тренеров здесь не меняются. ",
  scheduleLessonChangeDrawer_jsxText_cce698e3: "Подтвердить можно до ",
  scheduleLessonChangeDrawer_jsxText_cdb4ee2a: ". ",
  scheduleLessonChangeDrawer_jsxText_ed0812c0: "Пропущено занятий: ",
  scheduleLessonChangeDrawer_jsxText_fc3d1d5a: ". Первое: ",
  scheduleLessonChangeDrawer_label_182f7c57: "Зал",
  scheduleLessonChangeDrawer_label_232a0ead: "Дата",
  scheduleLessonChangeDrawer_label_2a326071: "Длительность",
  scheduleLessonChangeDrawer_label_66e7112f: "Это занятие",
  scheduleLessonChangeDrawer_label_6711f073: "Время",
  scheduleLessonChangeDrawer_label_a2706736: "Вся серия",
  scheduleLessonChangeDrawer_label_eafa287c: "С этого дня",
  scheduleLessonChangeDrawer_placeholder_d52c67f8: "Выберите зал",
  scheduleLessonChangeDrawer_string_4371fe93: "окончания срока предпросмотра",
  scheduleLessonChangeDrawer_string_5e90afd8: "только это занятие",
  scheduleLessonChangeDrawer_string_62b92aa4: "Обновить предпросмотр",
  scheduleLessonChangeDrawer_string_648188fd: "вся серия",
  scheduleLessonChangeDrawer_string_7242539b: "Не удалось проверить изменение занятия. Проверьте поля и попробуйте снова.",
  scheduleLessonChangeDrawer_string_857a90c1: "Получить предпросмотр",
  scheduleLessonChangeDrawer_string_9d63ad76: "с этого дня",
  scheduleLessonChangeDrawer_string_ab0f3256: " Будущие занятия будут пересчитаны.",
  scheduleLessonChangeDrawer_suffix_84d5d93d: " мин",
  scheduleLessonChangeDrawer_title_06a7be8a: "Изменить занятие",
  scheduleLessonChangeDrawer_windowConfirm_762d3769: "Отменить изменение занятия и потерять черновик?",
  scheduleMoreActionsSurface_ariaLabel_d3b1083d: "Закрыть дополнительные действия",
  scheduleMoreActionsSurface_jsxText_2071fb99: "Ещё ",
  scheduleMoreActionsSurface_jsxText_ca0bc1ad: "Ещё действий ",
  scheduleMoreActionsSurface_triggerLabel_0e137aa1: (value0: unknown) => "Ещё действий: " + String(value0) + "",
  scheduleOneOffCreateDrawer_jsxText_16568d17: "Создать занятие ",
  scheduleOneOffCreateDrawer_jsxText_21ebe345: "Проверьте занятие перед созданием",
  scheduleOneOffCreateDrawer_jsxText_8fbe9b75: "Отмена ",
  scheduleOneOffCreateDrawer_jsxText_a137f17a: "· ",
  scheduleOneOffCreateDrawer_jsxText_cce698e3: "Подтвердить можно до ",
  scheduleOneOffCreateDrawer_jsxText_cdb4ee2a: ". ",
  scheduleOneOffCreateDrawer_label_182f7c57: "Зал",
  scheduleOneOffCreateDrawer_label_232a0ead: "Дата",
  scheduleOneOffCreateDrawer_label_2a326071: "Длительность",
  scheduleOneOffCreateDrawer_label_6711f073: "Время",
  scheduleOneOffCreateDrawer_label_907efbd4: "Группа",
  scheduleOneOffCreateDrawer_placeholder_298a07c0: "Выберите группу",
  scheduleOneOffCreateDrawer_placeholder_d52c67f8: "Выберите зал",
  scheduleOneOffCreateDrawer_setFormError_39b8f8e7: "Не удалось проверить разовое занятие.",
  scheduleOneOffCreateDrawer_string_4371fe93: "окончания срока предпросмотра",
  scheduleOneOffCreateDrawer_string_52af7b72: "Проверьте предупреждение перед подтверждением.",
  scheduleOneOffCreateDrawer_string_62b92aa4: "Обновить предпросмотр",
  scheduleOneOffCreateDrawer_string_69d77b83: "Не удалось проверить разовое занятие. Проверьте поля и попробуйте снова.",
  scheduleOneOffCreateDrawer_string_857a90c1: "Получить предпросмотр",
  scheduleOneOffCreateDrawer_suffix_84d5d93d: " мин",
  scheduleOneOffCreateDrawer_title_4196b8be: "Разовое занятие",
  scheduleOneOffCreateDrawer_windowConfirm_f91e8f20: "Отменить создание занятия и потерять черновик?",
} as const
