export const fe4AttendanceText = {
  attendanceClientRow_jsxText_15d9dcc3: "Сначала дождитесь сохранения посещения ",
  attendanceClientRow_jsxText_76fc7876: "Профессионал",
  attendanceClientRow_jsxText_7730c85c: "Проблема с абонементом",
  attendanceClientRow_jsxText_a912ec86: "Карточка клиента ",
  attendanceClientRow_string_56e8a553: "Есть предупреждение по абонементу",
  attendanceClientRow_string_64add130: "Нужна проверка статуса абонемента",
  attendanceClientRow_string_81ee659f: "Профессиональный статус",
  attendanceClientRow_template_a4942e1b: (value0: unknown) => "Открыть карточку клиента " + String(value0) + "",
  attendanceContextControls_ariaLabel_47cce16a: "Следующая дата",
  attendanceContextControls_ariaLabel_669d9acd: "Предыдущая дата",
  attendanceContextControls_ariaLabel_b688b4c0: "Сегодня",
  attendanceContextControls_label_907efbd4: "Группа",
  attendanceContextControls_label_a06b48f8: "Дата тренировки",
  attendanceContextControls_placeholder_298a07c0: "Выберите группу",
  attendanceContextControls_string_58b83677: "Будущие даты недоступны",
  attendanceContextControls_string_f9b11001: "Дата вне доступного периода",
  attendanceProgress_jsxText_7f4adf31: "из ",
  attendanceProgress_jsxText_8dc8c1de: "Отмечено ",
  attendanceProgress_template_7363b38e: (value0: unknown, value1: unknown) => "Отмечено " + String(value0) + " из " + String(value1) + "",
  attendanceRosterViewControl_jsxText_4627639b: "Показывать клиентов",
  attendanceRosterViewControl_label_215816bf: "Все",
  attendanceRosterViewControl_label_7c7cca86: "Не отмечено",
  attendanceSaveStatus_jsxText_2fe8f2fd: "Сохранено",
  attendanceSaveStatus_jsxText_5189135a: "Повторить",
  attendanceSaveStatus_jsxText_90777d97: "Выберите состояние",
  attendanceSaveStatus_jsxText_9c27c381: "Сохраняем…",
  attendanceSaveStatus_jsxText_c5805f8b: "Не сохранено",
  attendanceScreen_changedFieldsJoin_21db14e4: " и ",
  attendanceScreen_description_823cc7d3: "Можно проверить сохраненные отметки или изменить их в полном списке.",
  attendanceScreen_description_acbeac4d: "Состав группы на эту дату пуст.",
  attendanceScreen_jsxText_1abc9cf0: "Не удалось обновить список после сохранения.",
  attendanceScreen_jsxText_1c26bf07: "Посещаемость занятия",
  attendanceScreen_jsxText_31de5844: "Повторить обновление списка",
  attendanceScreen_jsxText_752358df: "Показать всех",
  attendanceScreen_jsxText_9df82800: "Повторить загрузку групп",
  attendanceScreen_label_163a016f: "Обновить список",
  attendanceScreen_label_ccdc603e: "Загружаем доступные группы...",
  attendanceScreen_label_f63b7eb9: "Загружаем состав группы...",
  attendanceScreen_message_5530460b: "Список доступных групп обновлен.",
  attendanceScreen_setScopeChangeMessage_b4b5eb68: "Доступ к группе изменился",
  attendanceScreen_string_04540f1a: "Сервер не вернул сохраненное состояние.",
  attendanceScreen_string_11527668: "Главный тренер или суперадминистратор назначит группы, после этого они появятся здесь.",
  attendanceScreen_string_33b50a40: "Создайте группу и добавьте в нее клиентов, чтобы открыть сценарий отметки посещений.",
  attendanceScreen_string_3fab1709: "Назначенные группы отсутствуют",
  attendanceScreen_string_4f753af9: "Редактирование посещаемости недоступно.",
  attendanceScreen_string_60cfcc47: "Доступные группы пока отсутствуют",
  attendanceScreen_string_72edaa61: "Не удалось загрузить клиентов группы на выбранную дату.",
  attendanceScreen_string_78cbcd82: "дата изменена",
  attendanceScreen_string_8558b70f: "Сервер не разрешил изменять посещаемость этого занятия.",
  attendanceScreen_string_9fedff60: "группа изменена",
  attendanceScreen_string_aace5a72: "Нет групп для отметки посещений",
  attendanceScreen_string_ae751111: "Не удалось сохранить отметку.",
  attendanceScreen_string_cbea104a: "Отмененное занятие доступно только для просмотра.",
  attendanceScreen_string_e6a18bf5: "Не удалось загрузить доступные группы для посещений.",
  attendanceScreen_string_e7fdd82a: "Когда вам назначат группу, экран посещений автоматически покажет рабочий список.",
  attendanceScreen_string_e978a33c: "Будущее занятие доступно только для просмотра.",
  attendanceScreen_template_3fdd7a08: (value0: unknown) => "Редактирование недоступно: " + String(value0) + ".",
  attendanceScreen_template_97cc5be8: (value0: unknown) => "" + String(value0) + ". Контекст посещений выбран заново.",
  attendanceScreen_template_a4d8a706: (value0: unknown) => "Дата " + String(value0) + "",
  attendanceScreen_title_32340c90: "Все клиенты отмечены",
  attendanceScreen_title_59fc779f: "В выбранной группе пока нет клиентов",
  attendanceScreen_title_5f43e5f1: "Посещения",
  attendanceScreen_title_63e4ed16: "Группы для посещений не загрузились",
  attendanceScreen_title_d81f487a: "Список клиентов не загрузился",
  attendanceStateControl_label_7c7cca86: "Не отмечено",
  attendanceStateControl_label_cd2e8ad3: "Не был",
  attendanceStateControl_label_ff13de89: "Был",
  attendanceStateControl_template_63505065: (value0: unknown) => "Посещение: " + String(value0) + "",
  attendanceTodayWorklist_jsxText_a137f17a: "· ",
  attendanceTodayWorklist_jsxText_d4f85d36: "–",
} as const
