export const fe5ClientListText = {
  clientListFilters_label_0852baeb: "20 на странице",
  clientListFilters_label_5ea95729: "50 на странице",
  clientListFilters_label_ccbbc3d6: "100 на странице",
  clientListViewModel_accessibleName_50f65f53: (value0: unknown) => "Открыть клиента " + String(value0) + "",
  clientListViewModel_description_f6bf3dbb: "Нет подсказок от сервера",
  clientListViewModel_label_1139430b: "Абонемент",
  clientListViewModel_label_225077c6: "Статус",
  clientListViewModel_label_2f17c4d2: "Филиал",
  clientListViewModel_label_34886925: "В архиве",
  clientListViewModel_label_87a3edde: "Визит",
  clientListViewModel_label_907efbd4: "Группа",
  clientListViewModel_label_c19bb335: "Планово",
  clientListViewModel_label_ed73f50a: (value0: unknown) => "До " + String(value0) + "",
  clientListViewModel_label_fca8d5aa: "Контакты",
  clientListViewModel_string_0d836c15: "Не указан",
  clientListViewModel_string_19fc4b0c: "Скрыты",
  clientListViewModel_string_1fc40e1a: "Телефон не указан",
  clientListViewModel_string_202af31a: "Нет текущего абонемента",
  clientListViewModel_string_42be0520: "Без абонемента",
  clientListViewModel_string_48edd223: "Нет визитов",
  clientListViewModel_string_63e29a54: "Оформить абонемент",
  clientListViewModel_string_6bd8ee2e: "Плановое сопровождение",
  clientListViewModel_string_6c2aee20: "По факту",
  clientListViewModel_string_76fc7876: "Профессионал",
  clientListViewModel_string_81ee659f: "Профессиональный статус",
  clientListViewModel_string_9ed5aecd: "Без группы",
  clientListViewModel_string_a560016c: "Филиал не указан",
  clientListViewModel_string_a87a4b39: "Активен",
  clientListViewModel_string_b0e01526: "Отметка",
  clientListViewModel_string_b36bd7f1: "Оформление не начато",
  clientListViewModel_string_c3c76d85: "Без даты",
  clientListViewModel_string_f16cbd32: "Не указана",
  clientListViewModel_string_f409e458: "Несколько абонементов",
  clientListViewModel_template_0705739a: (value0: unknown) => "" + String(value0) + ", использован",
  clientListViewModel_template_1c66e7c6: (value0: unknown, value1: unknown) => "" + String(value0) + " в архиве из " + String(value1) + "",
  clientListViewModel_template_2564fff1: (value0: unknown, value1: unknown) => "" + String(value0) + " активных из " + String(value1) + "",
  clientListViewModel_template_538d6d18: (value0: unknown) => "" + String(value0) + "Без группы",
  clientListViewModel_template_8d3d1cda: (value0: unknown) => "" + String(value0) + " всего",
  clientPreviewPanel_ariaLabel_a0f74e3c: "Свернуть preview",
  clientPreviewPanel_jsxText_18e1009d: "Последние события ",
  clientPreviewPanel_jsxText_1e125223: "Нужно сейчас ",
  clientPreviewPanel_jsxText_3d64c6af: "Событий пока нет ",
  clientPreviewPanel_jsxText_3e0ccd92: "Сообщение ",
  clientPreviewPanel_jsxText_5189135a: "Повторить ",
  clientPreviewPanel_jsxText_63e29a54: "Оформить абонемент ",
  clientPreviewPanel_jsxText_82efa6ea: "Открыть карточку ",
  clientPreviewPanel_jsxText_ba936c58: "Посещение ",
  clientPreviewPanel_jsxText_e869584b: "Загружаем краткую карточку. ",
  clientPreviewPanel_jsxText_efa5d3cd: "Выберите клиента в списке. ",
  clientPreviewPanel_title_85a05a71: "Preview не загрузился",
  clientsListScreen_string_24dfeca0: "Краткая карточка",
  clientsListScreen_string_ff296dda: "Клиенты",
  clientsResults_ariaLabel_3ff6b7f9: "Размер страницы",
  clientsResults_jsxText_1139430b: "Абонемент",
  clientsResults_jsxText_1a9fb1f3: "Назад",
  clientsResults_jsxText_2f17c4d2: "Филиал",
  clientsResults_jsxText_3e622aec: "Клиент",
  clientsResults_jsxText_41006963: "Страница ",
  clientsResults_jsxText_5189135a: "Повторить ",
  clientsResults_jsxText_5ce0e345: "Следующее действие",
  clientsResults_jsxText_6e1f7baa: "Очистить поиск ",
  clientsResults_jsxText_ab5df625: "... ",
  clientsResults_jsxText_cd45ec78: "Сбросить фильтры ",
  clientsResults_jsxText_ea58bb0b: "Дальше",
  clientsResults_string_155e2d79: "Можно очистить поиск или сбросить расширенные фильтры отдельно.",
  clientsResults_string_1fc40e1a: "Телефон не указан",
  clientsResults_string_4c1f7bc0: "Клиенты не найдены",
  clientsResults_string_517609e1: "Клиентов пока нет.",
  clientsResults_string_6694f801: "Попробуйте изменить или сбросить расширенные фильтры.",
  clientsResults_string_8d588d9f: "Клиентов пока нет",
  clientsResults_string_a560016c: "Филиал не указан",
  clientsResults_string_c0936f1b: "Создайте первую карточку клиента.",
  clientsResults_string_df8d8576: "Попробуйте другой запрос или очистите поиск.",
  clientsResults_template_3a8e2e94: (value0: unknown) => "Выбрать клиента " + String(value0) + "",
  clientsResults_template_feafe754: (value0: unknown) => "Страница " + String(value0) + "",
  clientsResults_title_180fcaa4: "Не удалось загрузить клиентов",
  clientsToolbar_ariaLabel_fcf4cc1c: "Закрыть фильтры клиентов",
  clientsToolbar_jsxText_407f8717: "Сбросить ",
  clientsToolbar_jsxText_ef05d579: "Готово ",
  clientsToolbar_label_01440154: (value0: unknown) => "Истекает с " + String(value0) + "",
  clientsToolbar_label_163a016f: "Обновить список",
  clientsToolbar_label_20f55670: (value0: unknown) => "Статус: " + String(value0) + "",
  clientsToolbar_label_225077c6: "Статус",
  clientsToolbar_label_3ff6b7f9: "Размер страницы",
  clientsToolbar_label_5a2595c2: "Новый клиент",
  clientsToolbar_label_5c7aab91: "Истекает по",
  clientsToolbar_label_692fdce0: (value0: unknown) => "Истекает по " + String(value0) + "",
  clientsToolbar_label_907efbd4: "Группа",
  clientsToolbar_label_9c924cdc: "Истекает с",
  clientsToolbar_label_ddeb6381: (value0: unknown) => "Группа: " + String(value0) + "",
  clientsToolbar_label_f2549c72: "Без фото",
  clientsToolbar_placeholder_2a013601: "Все статусы",
  clientsToolbar_placeholder_d71b0c68: "Все группы",
  clientsToolbar_resetLabel_cd45ec78: "Сбросить фильтры",
  clientsToolbar_string_0e1206b8: "Имя клиента",
  clientsToolbar_string_4d848c10: "Имя или телефон",
  clientsToolbar_string_6890f945: "Поиск по имени или телефону",
  clientsToolbar_string_ae8e30fb: "Поиск по имени",
  clientsToolbar_string_ce01acee: "выбрана",
  clientsToolbar_title_ef76d1e3: "Фильтры клиентов",
  useClientsListState_string_180fcaa4: "Не удалось загрузить клиентов",
  useClientsListState_string_185d19a4: "Не удалось загрузить preview",
} as const
