export const fe6ClientProfileText = {
  clientAttendanceHistorySection_jsxText_001835f0: "По этому клиенту пока нет отмеченных посещений. ",
  clientAttendanceHistorySection_jsxText_511e94e0: "Показана текущая порция истории: ",
  clientAttendanceHistorySection_jsxText_7f4adf31: "из ",
  clientAttendanceHistorySection_jsxText_85242586: "История посещений",
  clientAttendanceHistorySection_jsxText_cdb4ee2a: ". ",
  clientAttendanceHistorySection_jsxText_f4f7179e: "История посещений появится здесь после загрузки данных. ",
  clientAttendanceHistorySection_jsxText_f8ba76ae: "Всего: ",
  clientAttendanceHistorySection_string_34866051: "Тренеру доступны только дата тренировки, назначенная группа и признак посещения.",
  clientAttendanceHistorySection_string_439e3b4c: "Отсутствовал",
  clientAttendanceHistorySection_string_8428fe4a: "Карточка показывает дату тренировки, группу и признак посещения.",
  clientAttendanceHistorySection_string_d78acecd: "Полная карточка",
  clientAttendanceHistorySection_string_f1cfa3af: "Присутствовал",
  clientAttendanceHistorySection_string_f46c76fc: "Режим тренера",
  clientAttendanceHistorySection_title_b7367866: "История пока не загружена",
  clientBirthDate_string_01bd4525: "ноября",
  clientBirthDate_string_05ae68ac: "января",
  clientBirthDate_string_2869fa11: "мая",
  clientBirthDate_string_3144ee44: "апреля",
  clientBirthDate_string_3ae2c0e9: "февраля",
  clientBirthDate_string_4ae69d9d: "августа",
  clientBirthDate_string_67cb393e: "сентября",
  clientBirthDate_string_6cfa0bb4: "марта",
  clientBirthDate_string_866b5e92: "декабря",
  clientBirthDate_string_a18a66ad: "июля",
  clientBirthDate_string_b4c08e7b: "июня",
  clientBirthDate_string_d80ff85c: "Не вычисляется",
  clientBirthDate_string_fd088563: "октября",
  clientBirthDate_template_2df85a9d: (value0: unknown) => "" + String(value0) + " лет",
  clientBirthDate_template_5d0c128d: (value0: unknown, value1: unknown, value2: unknown) => "" + String(value0) + " " + String(value1) + " " + String(value2) + " г.",
  clientBirthDate_template_9a991fb5: (value0: unknown) => "" + String(value0) + " года",
  clientBirthDate_template_a612da0b: (value0: unknown) => "" + String(value0) + " год",
  clientCreateScreen_description_8c274e30: "Форма появится после загрузки филиалов и групп.",
  clientCreateScreen_jsxText_fde25c93: "К списку клиентов ",
  clientCreateScreen_label_28f0dd24: "Готовим форму клиента...",
  clientCreateScreen_label_7c47f729: "Отменить",
  clientCreateScreen_message_67cfd459: "Базовая карточка клиента сохранена.",
  clientCreateScreen_setFormError_97732402: "Проверьте обязательные поля клиента и контактов.",
  clientCreateScreen_setFormError_bdd79cff: "Не удалось создать клиента. Попробуйте еще раз.",
  clientCreateScreen_string_85b97c29: "Не удалось загрузить список групп.",
  clientCreateScreen_submitLabel_40ba6630: "Сохранить клиента",
  clientCreateScreen_title_4f3100e0: "Клиент создан",
  clientCreateScreen_title_5a2595c2: "Новый клиент",
  clientCreateScreen_title_bb243bf5: "Не удалось подготовить форму",
  clientDetailScreen_jsxText_4ac45591: "Перевести ",
  clientDetailScreen_jsxText_59792556: "Редактировать ",
  clientDetailScreen_message_154f1c05: "Карточка клиента обновлена.",
  clientDetailScreen_message_43ee725f: "Текущий абонемент и история клиента обновлены.",
  clientDetailScreen_message_66eefff6: "Филиал и группа клиента обновлены.",
  clientDetailScreen_message_e33f1080: "Новая версия абонемента появилась в карточке клиента.",
  clientDetailScreen_setTransferFormError_3cbae865: "Не удалось перевести клиента.",
  clientDetailScreen_string_07dec05f: "Не удалось выполнить действие с абонементом.",
  clientDetailScreen_string_1ca66519: "В архив",
  clientDetailScreen_string_2f986cea: "Перевести клиента в архив?",
  clientDetailScreen_string_48186f7a: "Детали клиента",
  clientDetailScreen_string_592928a6: "Перевести в архив",
  clientDetailScreen_string_62845e23: "Клиент снова появится в активных списках и рабочих сценариях.",
  clientDetailScreen_string_63fa9b9e: "Не удалось загрузить карточку клиента.",
  clientDetailScreen_string_840e7ca3: "Карточка остается доступной для просмотра.",
  clientDetailScreen_string_9a24f729: "Клиент переведен в архив",
  clientDetailScreen_string_a1149493: "Клиент возвращен в активные",
  clientDetailScreen_string_a2e2cac2: "Не удалось загрузить филиалы и группы.",
  clientDetailScreen_string_b2b51d6b: "Вернуть в активные",
  clientDetailScreen_string_da7e2d4f: "Не удалось изменить статус клиента.",
  clientDetailScreen_string_ee9b8461: "Клиент снова помечен как активный.",
  clientDetailScreen_string_f868f3a1: "Клиент исчезнет из активных выборок, но карточка и история останутся доступны.",
  clientDetailScreen_string_f988138d: "Вернуть клиента в активные?",
  clientDetailScreen_string_fde25c93: "К списку клиентов",
  clientDetailScreen_title_3c069df0: "Абонемент продлен",
  clientDetailScreen_title_6c247ce7: "Карточка клиента не загрузилась",
  clientDetailScreen_title_7530f803: "Действие не выполнено",
  clientDetailScreen_title_7d8a509d: "Абонемент оформлен",
  clientDetailScreen_title_a6f3283a: "Клиент переведен",
  clientDetailScreen_title_db7198dc: "Данные абонемента исправлены",
  clientDetailSections_jsxText_167364bb: "До двух контактных лиц для экстренной связи. ",
  clientDetailSections_jsxText_353ad7d1: "Телефон: ",
  clientDetailSections_jsxText_6d7987c1: "Рабочая заметка",
  clientDetailSections_jsxText_80007feb: "Изменить группы ",
  clientDetailSections_jsxText_853f0e43: "Клиент пока не включен ни в одну группу. ",
  clientDetailSections_jsxText_ab308eef: "Группы клиента",
  clientDetailSections_jsxText_c50d9f78: "Контактные лица",
  clientDetailSections_jsxText_c8443a00: "Внутренняя заметка по клиенту, которая сохраняется в карточке. ",
  clientDetailSections_jsxText_d99fe020: "Рабочая заметка пока не добавлена. ",
  clientDetailSections_jsxText_de5e3108: "Контактные лица для клиента пока не добавлены. ",
  clientDetailSections_jsxText_f4ba7d70: "Блок показывает текущую привязку клиента к тренировочным группам. ",
  clientDetailSections_string_37180f56: "Время начала не указано",
  clientDetailSections_string_4f049897: "Неактивна",
  clientDetailSections_string_983ec130: "Активна",
  clientDetailSections_template_16812f5c: (value0: unknown) => "Старт: " + String(value0) + "",
  clientEditScreen_description_9c63e471: "Поля станут доступны после загрузки карточки и справочников.",
  clientEditScreen_jsxText_14a4b327: "К карточке клиента ",
  clientEditScreen_label_a2151f05: "Загружаем карточку клиента...",
  clientEditScreen_message_154f1c05: "Карточка клиента обновлена.",
  clientEditScreen_setFormError_97732402: "Проверьте обязательные поля клиента и контактов.",
  clientEditScreen_setFormError_e238fab9: "Не удалось сохранить изменения клиента.",
  clientEditScreen_string_63fa9b9e: "Не удалось загрузить карточку клиента.",
  clientEditScreen_string_a912ec86: "Карточка клиента",
  clientEditScreen_submitLabel_744cf2b2: "Сохранить изменения",
  clientEditScreen_title_6c247ce7: "Карточка клиента не загрузилась",
  clientEditScreen_title_f436b337: "Изменения сохранены",
  clientForm_jsxText_14efba42: "Контактные лица пока не добавлены. ",
  clientForm_jsxText_2c73c938: "Контакт #",
  clientForm_jsxText_63492f28: "Добавить контакт ",
  clientForm_jsxText_a00f32e0: "Можно указать до двух контактов. Пустые строки не будут сохранены. ",
  clientForm_jsxText_c50d9f78: "Контактные лица",
  clientForm_label_1a4f2dd4: "Тип контакта",
  clientForm_label_1ae72066: "Дата рождения",
  clientForm_label_1da7e937: "Имя",
  clientForm_label_2f17c4d2: "Филиал",
  clientForm_label_353eafa3: "Фамилия",
  clientForm_label_3ab1fb44: "ФИО контактного лица",
  clientForm_label_6d7987c1: "Рабочая заметка",
  clientForm_label_822f9fd9: "Телефон",
  clientForm_label_a49c980a: "Телефон контакта",
  clientForm_label_ab308eef: "Группы клиента",
  clientForm_label_e1739d0a: "Отчество",
  clientForm_placeholder_0e86ea4c: "Например: предпочитает связь после 18:00, важные детали по посещениям или оплате.",
  clientForm_placeholder_29def5ac: "+7(999) 000-00-00",
  clientForm_placeholder_37f3ddd4: "Иванов",
  clientForm_placeholder_4c5ee5d8: "Выберите филиал",
  clientForm_placeholder_52028dbd: "Иванович",
  clientForm_placeholder_59073e3a: "+7(999) 000-00-01",
  clientForm_placeholder_a3f088c6: "Мама / Папа / Другой",
  clientForm_placeholder_cc078195: "Иван",
  clientForm_placeholder_e23f3a45: "Анна Иванова",
  clientForm_string_3d8d006f: "Выберите группы",
  clientForm_string_74f8ad03: "Сначала выберите филиал",
  clientForm_template_8b452ad2: (value0: unknown) => "Удалить контакт " + String(value0) + "",
  clientForm_title_09e1875e: "Сохранение не выполнено",
  clientManagementForm_string_13f09c7f: "Укажите телефон клиента.",
  clientManagementForm_string_259085f9: "Укажите ФИО контактного лица.",
  clientManagementForm_string_735598db: "Укажите телефон контактного лица.",
  clientManagementForm_string_91e74fb3: "Укажите хотя бы одно из полей ФИО клиента.",
  clientManagementForm_string_acb35e79: "Можно сохранить не более двух контактных лиц.",
  clientManagementForm_string_db15274f: "нового клиента",
  clientManagementForm_string_f638f9f2: "Укажите тип контактного лица.",
  clientManagementFormatting_partsPush_4ebaca56: "архивный",
  clientManagementFormatting_partsPush_bd36839e: "неактивна",
  clientManagementFormatting_string_00f9729f: "Индивидуальная сумма",
  clientManagementFormatting_string_50f59e98: "Допустимы только JPEG, PNG, WebP, HEIC и HEIF.",
  clientManagementFormatting_string_5536d11b: "Файл больше 10 MB. Выберите фотографию меньшего размера.",
  clientManagementFormatting_string_62c745d0: "По факту использования",
  clientManagementFormatting_string_92f64d0d: "Без варианта каталога",
  clientManagementFormatting_string_a3c07b6d: "Версия абонемента",
  clientManagementFormatting_string_ba4d4bf6: "Не указано",
  clientManagementFormatting_string_de5a7f2f: "Каталожная цена",
  clientManagementFormatting_string_f16cbd32: "Не указана",
  clientOverviewSection_jsxText_76fc7876: "Профессионал",
  clientOverviewSection_jsxText_8afc6d90: "Видны фото, ФИО, рабочая заметка, назначенные группы и история посещений. ",
  clientOverviewSection_label_1ae72066: "Дата рождения",
  clientOverviewSection_label_1da7e937: "Имя",
  clientOverviewSection_label_2f17c4d2: "Филиал",
  clientOverviewSection_label_353eafa3: "Фамилия",
  clientOverviewSection_label_35c7d5b1: "Возраст",
  clientOverviewSection_label_48df6512: "Посещений",
  clientOverviewSection_label_822f9fd9: "Телефон",
  clientOverviewSection_label_894707a3: "Последнее посещение",
  clientOverviewSection_label_cd8c5873: "Группы",
  clientOverviewSection_label_e1739d0a: "Отчество",
  clientOverviewSection_label_fca8d5aa: "Контакты",
  clientOverviewSection_string_0d836c15: "Не указан",
  clientOverviewSection_string_28997f75: "Не выбраны",
  clientOverviewSection_string_39b10095: "Не добавлены",
  clientOverviewSection_string_3e622aec: "Клиент",
  clientOverviewSection_string_7c5ffdd7: "Загружаются",
  clientOverviewSection_string_81ee659f: "Профессиональный статус",
  clientOverviewSection_string_9edc2ad9: "Нет доступных групп",
  clientOverviewSection_string_ba4d4bf6: "Не указано",
  clientOverviewSection_string_ed0b220c: "Клиент тренера",
  clientOverviewSection_string_f16cbd32: "Не указана",
  clientOverviewSection_title_09f75b9f: "Доступ тренера",
  clientSharedInfo_jsxText_5e85c193: "Проверьте способ расчёта и фактическую сумму. Эти данные сохранятся в истории продажи. ",
  clientSharedInfo_jsxText_7c47f729: "Отменить ",
  clientSharedInfo_jsxText_bb3893c5: "Группы абонемента ",
  clientSharedInfo_jsxText_cc77c58c: "Подтвердить продажу ",
  clientSharedInfo_label_1413919e: "Способ расчёта",
  clientSharedInfo_label_625ac7ac: "Фактическая сумма",
  clientSharedInfo_label_6611d56d: "Дата оплаты",
  clientSharedInfo_string_68f7b035: "Отчётность · ",
  clientSharedInfo_string_d77dfdcd: "Не выбран",
  clientSharedInfo_string_f16cbd32: "Не указана",
  clientSharedInfo_title_d1df3de6: "Подтвердить новую продажу?",
  clientTransferModal_branchId_02733009: "Выберите целевой филиал.",
  clientTransferModal_jsxText_7c47f729: "Отменить ",
  clientTransferModal_jsxText_a8186ce3: "Перевести клиента ",
  clientTransferModal_label_4ebcb19f: "Текущая группа",
  clientTransferModal_label_9caac9e2: "Целевой филиал",
  clientTransferModal_label_c9fd9fc0: "Новая группа",
  clientTransferModal_label_e054a7e5: "Текущий филиал",
  clientTransferModal_string_00d475e1: "Загружаем филиалы",
  clientTransferModal_string_0d836c15: "Не указан",
  clientTransferModal_string_49b5e8d1: "Можно оставить без группы",
  clientTransferModal_string_4c5ee5d8: "Выберите филиал",
  clientTransferModal_string_74f8ad03: "Сначала выберите филиал",
  clientTransferModal_string_9ed5aecd: "Без группы",
  clientTransferModal_title_3451ed5f: "Перевод не выполнен",
  clientTransferModal_title_5df21aa1: "Перевод клиента",
} as const
