export const fe7ClientMembershipText = {
  clientMembershipSection_active_a87a4b39: "Активен",
  clientMembershipSection_expired_85d3fd5f: "Истёк",
  clientMembershipSection_future_a01345ca: "Будущий",
  clientMembershipSection_jsxText_10110ccf: "Текущих абонементов нет. ",
  clientMembershipSection_jsxText_2239797e: "Версий: ",
  clientMembershipSection_jsxText_55ab75c7: "Изменения срока, суммы и оплаты по клиенту. ",
  clientMembershipSection_jsxText_659ad690: "Продлить ",
  clientMembershipSection_jsxText_71606622: "Абонемент без групп не даёт доступ. Исправьте группы перед использованием. ",
  clientMembershipSection_jsxText_9a0b1924: "Абонемент без групп ",
  clientMembershipSection_jsxText_a946d490: "Новый абонемент ",
  clientMembershipSection_jsxText_bf6f178a: "История абонемента",
  clientMembershipSection_jsxText_d71b0c68: "Все группы ",
  clientMembershipSection_label_46a0edbb: "Сумма",
  clientMembershipSection_label_6611d56d: "Дата оплаты",
  clientMembershipSection_label_b3ae4c00: "Расчёт",
  clientMembershipSection_legacyTargetMissing_214235ce: "Без групп",
  clientMembershipSection_string_68f7b035: "Отчётность · ",
  clientMembershipSection_string_8d0e3e8b: "Исправить",
  clientMembershipSection_string_de3830e7: "Исправить группы",
  clientMembershipSection_usedSingleVisit_a091d291: "Разовое использовано",
  membershipCorrectionPanel_jsxText_375934ac: "Сохранить исправление ",
  membershipCorrectionPanel_jsxText_489f430b: "Подставить срок по правилу ",
  membershipCorrectionPanel_jsxText_529702bf: "Тип и цена зафиксированы в продаже и не меняются при исправлении. ",
  membershipCorrectionPanel_jsxText_7c47f729: "Отменить ",
  membershipCorrectionPanel_jsxText_7d3a232e: "Исправить текущий абонемент",
  membershipCorrectionPanel_jsxText_b3977315: "Исправление ",
  membershipCorrectionPanel_label_1139430b: "Абонемент",
  membershipCorrectionPanel_label_65ce6ae7: "Дата покупки",
  membershipCorrectionPanel_label_b9094c16: "Действует по",
  membershipCorrectionPanel_label_c94a6d0e: "Сумма продажи",
  membershipCorrectionPanel_label_f79d7e9d: "Действует с",
  membershipCorrectionPanel_string_1b5e4eb6: "Дата предложена автоматически, но ее можно изменить.",
  membershipCorrectionPanel_string_46bd9402: "Не удалось загрузить группы.",
  membershipCorrectionPanel_string_56f2dc95: "Рассчитываем дату окончания...",
  membershipCorrectionPanel_string_95777141: "Для разового посещения дату можно оставить пустой.",
  membershipCorrectionPanel_string_ae65fc7f: "Не удалось рассчитать срок абонемента.",
  membershipForms_string_0a04a7f3: "Укажите дату окончания.",
  membershipForms_string_55dc184c: "Можно выбрать не больше 5 групп",
  membershipForms_string_95193c08: "Выберите хотя бы одну группу",
  membershipForms_string_c17309b4: "Укажите дату оплаты.",
  membershipForms_string_c6401e27: "Укажите начало срока.",
  membershipForms_string_f603ddac: "Разовое посещение действует только в одной группе",
  membershipGroupTransferSurface_jsxText_01c7a7e5: "Перенести группу в абонементах",
  membershipGroupTransferSurface_jsxText_0d3bdb14: "Операция не создаёт продажу и не меняет цену или оплату. ",
  membershipGroupTransferSurface_jsxText_4b8e058e: "Показать предпросмотр ",
  membershipGroupTransferSurface_jsxText_52992c28: "Перенести группу ",
  membershipGroupTransferSurface_jsxText_7c4fbae8: "Нет затронутых абонементов.",
  membershipGroupTransferSurface_label_1105fc2c: "Целевая группа",
  membershipGroupTransferSurface_label_4fae346e: "Было",
  membershipGroupTransferSurface_label_66e855e0: "Станет",
  membershipGroupTransferSurface_label_874977d3: "Исходная группа",
  membershipGroupTransferSurface_placeholder_298a07c0: "Выберите группу",
  membershipGroupTransferSurface_setError_265d66a7: "Выберите исходную и целевую группу.",
  membershipGroupTransferSurface_string_46bd9402: "Не удалось загрузить группы.",
  membershipGroupTransferSurface_string_68f7b035: "Отчётность · ",
  membershipGroupTransferSurface_string_8d75ef84: "Не удалось перенести группу.",
  membershipGroupTransferSurface_string_f6f37b0e: "Загружаем группы...",
  membershipGroupTransferSurface_string_fb5e8413: "Не удалось построить предпросмотр.",
  membershipHistory_jsxText_3973e022: "-",
  membershipHistory_jsxText_4212693d: "Событие",
  membershipHistory_jsxText_46a0edbb: "Сумма",
  membershipHistory_jsxText_638d02d7: "Дата версии",
  membershipHistory_jsxText_6611d56d: "Дата оплаты",
  membershipHistory_jsxText_7a2b2927: "История появится после первого действия с абонементом. ",
  membershipHistory_jsxText_81f1186d: "Версия: ",
  membershipHistory_jsxText_9a0b1924: "Абонемент без групп ",
  membershipHistory_jsxText_a137f17a: "· ",
  membershipHistory_jsxText_cd8c5873: "Группы",
  membershipHistory_jsxText_e97ca72e: "Период",
  membershipHistory_jsxText_fb305b47: "Текущая ",
  membershipHistory_string_68f7b035: "Отчётность · ",
  membershipPurchasePanel_jsxText_00a991e3: "Оформить новый абонемент",
  membershipPurchasePanel_jsxText_63e29a54: "Оформить абонемент ",
  membershipPurchasePanel_jsxText_7c47f729: "Отменить ",
  membershipPurchasePanel_jsxText_a0517045: "Выберите способ расчёта и подтвердите фактическую сумму этой продажи. ",
  membershipPurchasePanel_label_b9094c16: "Действует по",
  membershipPurchasePanel_label_e7a31570: "Комментарий к профессиональному абонементу",
  membershipPurchasePanel_label_f79d7e9d: "Действует с",
  membershipPurchasePanel_string_1284aff0: "Не удалось загрузить абонементы.",
  membershipPurchasePanel_string_46bd9402: "Не удалось загрузить группы.",
  membershipPurchasePanel_string_548872bd: "Укажите комментарий.",
  membershipPurchasePanel_string_c17309b4: "Укажите дату оплаты.",
  membershipPurchasePanel_string_c6401e27: "Укажите начало срока.",
  membershipPurchasePanel_string_fc65fc7d: "Укажите окончание срока.",
  membershipRenewPanel_jsxText_3ec61459: "Новая продажа ",
  membershipRenewPanel_jsxText_45df77cf: "Предыдущая продажа показана только для контекста. Выберите способ расчёта заново. ",
  membershipRenewPanel_jsxText_53d9b68d: "Продлить текущий абонемент",
  membershipRenewPanel_jsxText_7c47f729: "Отменить ",
  membershipRenewPanel_jsxText_b62f978a: "Продлить абонемент ",
  membershipRenewPanel_label_69e09d39: "Предыдущая продажа",
  membershipRenewPanel_label_7e076a01: "Предыдущий период",
  membershipRenewPanel_label_c0aa51ea: "Предыдущий расчёт",
  membershipRenewPanel_label_e7a31570: "Комментарий к профессиональному абонементу",
  membershipRenewPanel_string_1284aff0: "Не удалось загрузить абонементы.",
  membershipRenewPanel_string_46bd9402: "Не удалось загрузить группы.",
  membershipRenewPanel_string_c17309b4: "Укажите дату оплаты.",
  membershipSaleComment_jsxText_5b353773: "Комментарий к покупке",
  membershipSaleComment_jsxText_9adae390: "Комментарий пока не добавлен. ",
  membershipSaleComment_jsxText_a137f17a: "· ",
  membershipSaleComment_jsxText_b4d30cae: "Сохранить ",
  membershipSaleComment_string_39ad24b1: "Сервер не вернул обновлённый комментарий покупки.",
  membershipSaleComment_string_59792556: "Редактировать",
  membershipSaleComment_string_79e9f1b7: "Отменить редактирование",
  membershipSaleComment_string_8fbe9b75: "Отмена",
  membershipSaleComment_string_b091246d: "Редактировать комментарий",
  membershipSaleComment_string_de79692d: "Не удалось сохранить комментарий.",
  membershipSaleComment_template_359b5242: (value0: unknown, value1: unknown) => "" + String(value0) + " к покупке от " + String(value1) + "",
  membershipSalePricing_amountOnly_92f64d0d: "Без варианта каталога",
  membershipSalePricing_catalog_f2cb507f: "По каталожной цене",
  membershipSalePricing_catalogOverride_00f9729f: "Индивидуальная сумма",
  membershipSalePricing_string_4ec1f493: "Выберите абонемент.",
  membershipSalePricing_string_68bb61b1: "Укажите положительную сумму целыми рублями.",
  membershipSalePricing_string_a81f5813: "Выберите способ расчёта.",
  membershipSalePricingFields_jsxText_de5a7f2f: "Каталожная цена ",
  membershipSalePricingFields_label_7d7837d2: (value0: unknown, value1: unknown) => "" + String(value0) + " • " + String(value1) + "",
  membershipSalePricingFields_label_acf9468c: "Способ расчёта суммы",
  membershipSalePricingFields_label_ee4d70c4: "Фактическая сумма продажи, ₽",
  membershipSalePricingFields_string_38cc78d4: "Вариант абонемента",
  membershipSalePricingFields_string_6a823a40: "Абонемент будет оформлен без выбора варианта каталога. Срок задается отдельно.",
  membershipSalePricingFields_string_70431854: "Введите фактическую сумму этой продажи.",
  membershipSalePricingFields_string_cbcc2c45: "Выберите вариант",
  membershipSalePricingFields_string_ef27abbb: "Загружаем...",
  membershipTargetGroupsField_commit_2457468a: (value0: unknown, value1: unknown) => "Группа " + String(value0) + " перемещена на позицию " + String(value1) + ".",
  membershipTargetGroupsField_commit_4cc8c7c2: (value0: unknown) => "Группа " + String(value0) + " добавлена.",
  membershipTargetGroupsField_commit_e797a592: (value0: unknown) => "Группа " + String(value0) + " удалена.",
  membershipTargetGroupsField_jsxText_3049ac8a: "Отчётность ",
  membershipTargetGroupsField_jsxText_b558d46f: "Доступ остаётся ко всем группам; выбранные группы нужны для отчётности. ",
  membershipTargetGroupsField_jsxText_bb3893c5: "Группы абонемента",
  membershipTargetGroupsField_jsxText_e8d73d0d: "Нет выбранных групп. ",
  membershipTargetGroupsField_label_90ad60fb: "Добавить группу",
  membershipTargetGroupsField_string_11585e1a: "Разовое посещение действует только в выбранной группе.",
  membershipTargetGroupsField_string_240a0407: "Выберите от 1 до 5 групп одного филиала. Первая группа используется в финансовой разбивке.",
  membershipTargetGroupsField_string_3b566ca7: "Найдите группу",
  membershipTargetGroupsField_string_96ed57be: "Выбрано 5 групп",
  membershipTargetGroupsField_string_f6f37b0e: "Загружаем группы...",
  membershipTargetGroupsField_template_27219159: (value0: unknown) => "Удалить группу " + String(value0) + "",
  membershipTargetGroupsField_template_46df310f: (value0: unknown) => "Опустить группу " + String(value0) + "",
  membershipTargetGroupsField_template_ed679b96: (value0: unknown) => "Поднять группу " + String(value0) + "",
} as const
