export const fe8ClientMessengerMediaText = {
  clientMessengerChatSection_failed_bf22dfee: "Ошибка",
  clientMessengerChatSection_getApiErrorMessage_850ac5ad: "Не удалось создать ссылку подключения.",
  clientMessengerChatSection_jsxText_010ff624: "Загрузить еще ",
  clientMessengerChatSection_jsxText_0465921b: "Ссылка и QR ",
  clientMessengerChatSection_jsxText_0994139f: "Чат подключен, сообщений пока нет. ",
  clientMessengerChatSection_jsxText_3b46e89c: "Доступ только для чтения. Отправка сообщений доступна администратору. ",
  clientMessengerChatSection_jsxText_420572a1: "Отправить в Telegram ",
  clientMessengerChatSection_jsxText_5189135a: "Повторить ",
  clientMessengerChatSection_jsxText_603e460b: "Обновить ",
  clientMessengerChatSection_jsxText_97b87834: "Действует до ",
  clientMessengerChatSection_jsxText_a9a7ca66: "Чат подключен",
  clientMessengerChatSection_jsxText_af9f52ba: "Отправьте клиенту ссылку или дайте отсканировать QR-код. ",
  clientMessengerChatSection_jsxText_bb442dee: "Загружаем переписку... ",
  clientMessengerChatSection_jsxText_c3641f85: "@",
  clientMessengerChatSection_jsxText_dc120821: "Поделиться ",
  clientMessengerChatSection_jsxText_fb72b78f: "Открыть Telegram ",
  clientMessengerChatSection_placeholder_aac0c410: "Введите сообщение клиенту",
  clientMessengerChatSection_queued_b22a2454: "В очереди",
  clientMessengerChatSection_received_06124cee: "Получено",
  clientMessengerChatSection_sending_9ef21e53: "Отправка",
  clientMessengerChatSection_sentToTelegram_13b9719a: "Отправлено",
  clientMessengerChatSection_setLinkCopyError_fe355f11: "Не удалось скопировать автоматически. Выделите ссылку и скопируйте вручную.",
  clientMessengerChatSection_setLinkShareError_b9df5845: "Не удалось открыть системное меню. Отправьте ссылку в Telegram или скопируйте ее.",
  clientMessengerChatSection_string_1fe35c6e: "Telegram-чат клиента",
  clientMessengerChatSection_string_2a93cc16: "Ожидаем подключение клиента",
  clientMessengerChatSection_string_33c27632: "Не удалось загрузить переписку.",
  clientMessengerChatSection_string_3e622aec: "Клиент",
  clientMessengerChatSection_string_43bf26a8: "Не удалось загрузить более ранние сообщения.",
  clientMessengerChatSection_string_4b14a61e: "Сгенерируйте ссылку или покажите QR-код, чтобы клиент начал диалог.",
  clientMessengerChatSection_string_64db2165: "Клиент еще не подключил Telegram",
  clientMessengerChatSection_string_8192855b: "Отправка...",
  clientMessengerChatSection_string_89439c68: "дата не указана",
  clientMessengerChatSection_string_8d810136: "Скопировать ссылку",
  clientMessengerChatSection_string_9372e5cf: "Доступ к переписке появится после подключения клиента.",
  clientMessengerChatSection_string_a78ea756: "Не удалось отправить сообщение.",
  clientMessengerChatSection_string_c917e434: "Клиент еще не открыл чат в Telegram.",
  clientMessengerChatSection_string_ceb68a92: "Отправить",
  clientMessengerChatSection_string_d2d08c71: "Скопировано",
  clientMessengerChatSection_string_d33ec712: "Telegram не подключен.",
  clientMessengerChatSection_telegramShareText_b8bb4077: "Откройте ссылку, чтобы подключить Telegram-чат к CRM.",
  clientMessengerChatSection_template_e9da7455: (value0: unknown) => "Ожидаем подключение до " + String(value0) + "",
  clientMessengerChatSection_title_2d65bc85: "Подключение Telegram",
  clientMessengerChatSection_title_c3386376: "Переписка не загрузилась",
  clientNoteAttribution_jsxText_a137f17a: "· ",
  clientPhotoSection_jsxText_5f0835c4: "JPEG, PNG, WebP, HEIC, HEIF до 10 MB. ",
  clientPhotoSection_jsxText_69380add: "Загружено: ",
  clientPhotoSection_jsxText_7ef83fc5: "Фото пока не показано",
  clientPhotoSection_message_9eb96d58: "Карточка клиента получила новую фотографию.",
  clientPhotoSection_string_111213e7: "Загрузка",
  clientPhotoSection_string_232091bb: "Фото доступно для просмотра.",
  clientPhotoSection_string_45c2f1fa: "Фото",
  clientPhotoSection_string_5d9e3868: "Не удалось загрузить фотографию клиента.",
  clientPhotoSection_string_62530367: "Сначала сохраните клиента, затем вернитесь в карточку или редактирование, чтобы загрузить фотографию.",
  clientPhotoSection_string_6c6732f0: "Фото можно добавить сразу после первичного сохранения карточки клиента.",
  clientPhotoSection_string_75f5b4ed: "Фотография клиента",
  clientPhotoSection_string_b96af1f1: "Фотография еще не загружена или недоступна для просмотра.",
  clientPhotoSection_string_bee0c752: "Загрузить фото",
  clientPhotoSection_string_f1163738: "Просмотр",
  clientPhotoSection_string_f61eb235: "Заменить фото",
  clientPhotoSection_string_f71f0281: "Можно заменить фото клиента.",
  clientPhotoSection_template_8864f585: (value0: unknown) => "Открыть фотографию клиента " + String(value0) + "",
  clientPhotoSection_template_b53a862a: (value0: unknown) => "Фотография клиента " + String(value0) + "",
  clientPhotoSection_title_0f50b2a8: "Фото не загружено",
  clientPhotoSection_title_2fb80bcc: "Фотография обновлена",
} as const
