export const fe9AttentionText = {
  attentionDashboard_title_f17ceff0: "Внимание",
  attentionPanel_ariaLabel_93096e67: "Причины",
  attentionPanel_jsxText_0701381c: "Позвонить ",
  attentionPanel_jsxText_18c7acca: "Карточка ",
  attentionPanel_jsxText_3a45c61a: ". Нажмите «Связались», чтобы повторить. ",
  attentionPanel_jsxText_6fad7653: "Проверено: ",
  attentionPanel_jsxText_a912ec86: "Карточка клиента ",
  attentionPanel_jsxText_b4533fb8: "Список клиентов ",
  attentionPanel_jsxText_b625bade: "Просрочен: ",
  attentionPanel_jsxText_bffdeff3: "Причина не указана",
  attentionPanel_jsxText_f8ba76ae: "Всего: ",
  attentionPanel_label_34e77243: "Загружаем клиентов...",
  attentionPanel_label_4cd3b5b4: (value0: unknown) => "Пропущено подряд: " + String(value0) + "",
  attentionPanel_label_5189135a: "Повторить",
  attentionPanel_string_043dabe8: "Истекает сегодня",
  attentionPanel_string_1fc40e1a: "Телефон не указан",
  attentionPanel_string_20df618a: "Нет заметок",
  attentionPanel_string_5047bc55: "Группы не указаны",
  attentionPanel_string_53217635: "Истек",
  attentionPanel_string_748dc44e: "дня",
  attentionPanel_string_76848548: "Нет данных",
  attentionPanel_string_8173243b: "Истек сегодня",
  attentionPanel_string_82dd6ade: "Связались",
  attentionPanel_string_8eae90e5: "день",
  attentionPanel_string_92e9102e: "Скоро истечет",
  attentionPanel_string_9c27c381: "Сохраняем…",
  attentionPanel_string_bb034c97: "Дата окончания прошла",
  attentionPanel_string_c27d559b: "дней",
  attentionPanel_string_e77d1c5f: "Срок окончания приближается",
  attentionPanel_template_0ad31512: (value0: unknown) => "Связались с " + String(value0) + "",
  attentionPanel_template_1182acc1: (value0: unknown, value1: unknown) => "Истек " + String(value0) + " " + String(value1) + " назад",
  attentionPanel_template_15a88e60: (value0: unknown) => "Всего клиентов: " + String(value0) + "",
  attentionPanel_template_427c7cbf: (value0: unknown) => "Просроченных абонементов: " + String(value0) + "",
  attentionPanel_template_50ce20af: (value0: unknown) => "Открыть Telegram " + String(value0) + "",
  attentionPanel_template_a35598f8: (value0: unknown) => "Сохраняем связь с " + String(value0) + "",
  attentionPanel_template_a98de9df: (value0: unknown) => "Открыть карточку " + String(value0) + "",
  attentionPanel_template_c6ca6019: (value0: unknown) => "Другие действия для " + String(value0) + "",
  attentionPanel_template_ccba39cd: (value0: unknown, value1: unknown) => "Осталось " + String(value0) + " " + String(value1) + "",
  attentionPanel_template_e50e96fc: (value0: unknown) => "Позвонить " + String(value0) + "",
  attentionPanel_template_f3d8e459: (value0: unknown, value1: unknown) => "" + String(value0) + ": " + String(value1) + "",
} as const
