namespace GymCrm.Api.Auth;

internal sealed record ClientMembershipResponse(
    Guid Id,
    Guid SaleId,
    Guid MembershipCatalogItemId,
    string MembershipName,
    string BehaviorKind,
    DateOnly PurchaseDate,
    DateOnly? ExpirationDate,
    DateOnly? IndividualValidFrom,
    DateOnly? IndividualValidTo,
    string? ProfessionalComment,
    decimal PaymentAmount,
    bool IsPaid,
    bool SingleVisitUsed,
    Guid? PaidByUserId,
    string? PaidByUserFullName,
    DateTimeOffset? PaidAt,
    string ChangeReason,
    DateTimeOffset ValidFrom,
    DateTimeOffset? ValidTo,
    DateTimeOffset CreatedAt,
    ClientMembershipFinancialSummaryResponse FinancialSummary,
    IReadOnlyList<ClientMembershipRefundResponse> Refunds);
