namespace GymCrm.Api.Auth;

internal sealed record ClientMembershipResponse(
    Guid Id,
    Guid SaleId,
    Guid? MembershipCatalogItemId,
    string MembershipName,
    string BehaviorKind,
    string PricingMode,
    decimal GrossAmount,
    decimal? CatalogPrice,
    DateOnly PurchaseDate,
    DateOnly PaymentDate,
    DateOnly? ExpirationDate,
    DateOnly? IndividualValidFrom,
    DateOnly? IndividualValidTo,
    string? ProfessionalComment,
    bool SingleVisitUsed,
    Guid PaymentRecordedByUserId,
    string PaymentRecordedByUserName,
    DateTimeOffset PaymentRecordedAt,
    string ChangeReason,
    DateTimeOffset ValidFrom,
    DateTimeOffset? ValidTo,
    DateTimeOffset CreatedAt,
    string CoverageKind,
    string EntitlementState,
    IReadOnlyList<ClientMembershipTargetGroupResponse> TargetGroups,
    string? Comment,
    string? CommentLastChangedByName,
    DateTimeOffset? CommentLastChangedAt,
    ClientMembershipFinancialSummaryResponse FinancialSummary,
    IReadOnlyList<ClientMembershipRefundResponse> Refunds);

internal sealed record ClientMembershipTargetGroupResponse(
    Guid GroupId,
    string GroupName,
    Guid BranchId,
    string BranchName,
    int Position,
    bool IsActive);
