namespace GymCrm.Api.Auth;

internal sealed record ClientListItemResponse(
    Guid Id,
    string? LastName,
    string? FirstName,
    string? MiddleName,
    string FullName,
    string Phone,
    Guid BranchId,
    string BranchName,
    string Status,
    IReadOnlyList<Guid> GroupIds,
    IReadOnlyList<ClientGroupSummaryResponse> Groups,
    int ContactCount,
    ClientPhotoSummaryResponse? Photo,
    bool IsProfessional,
    string? ProfessionalComment,
    bool HasActiveMembership,
    IReadOnlyList<ClientMembershipResponse> CurrentMemberships,
    bool HasCurrentMembership,
    string MembershipState,
    DateOnly? LastVisitDate,
    IReadOnlyList<ClientActionHintResponse> ActionHints,
    DateTimeOffset UpdatedAt);
