import type { ThemeProfile } from './types'
import { createFoundationVariables } from './foundations'

export type SemanticVariableMap = Record<`--crm-${string}`, string>

export const semanticBaseColors = {
  background: '#F6F4EE',
  backgroundAlt: '#EDF2EE',
  surface: '#FFFFFF',
  surfaceSubtle: '#F6FAF7',
  surfaceMuted: '#F7F8FA',
  surfaceDisabled: '#F3F4F6',
  text: '#17312D',
  textStrong: '#111827',
  textDisabled: '#596862',
  muted: '#64736D',
  border: '#D7E0DA',
  borderMuted: '#E5E7EB',
  borderStrong: '#B8C8BF',
  success: '#2F8F6B',
  successFg: '#1F6F53',
  warning: '#C98A2E',
  warningFg: '#8A5A11',
  danger: '#C95345',
  dangerFg: '#A7352A',
  info: '#2563EB',
  infoFg: '#1D4ED8',
  neutralFg: '#4B5563',
  authAction: '#F26A21',
  authActionHover: '#D95C1F',
  authActionActive: '#BF4D17',
  authText: '#171D27',
  authMuted: '#687083',
  authIconMuted: '#62708A',
  authBorder: '#D7DEE7',
  authSolidBackground: '#07100F',
  scheduleRose: '#C95370',
  scheduleSlate: '#718096',
} as const

function alpha(color: string, percent: number) {
  return `color-mix(in srgb, ${color} ${percent}%, transparent)`
}

export function createSemanticVariables(
  profile: ThemeProfile,
): SemanticVariableMap {
  const primary = profile.main.primary
  const secondary = profile.main.secondary ?? primary
  const neutral = profile.supplementary[0]
  const accentThree = profile.supplementary[1] ?? primary
  const accentFour = profile.supplementary[2] ?? secondary

  return {
    ...createFoundationVariables(),

    '--crm-brand-primary': primary[6],
    '--crm-brand-primary-hover': primary[7],
    '--crm-brand-primary-active': primary[8],
    '--crm-brand-primary-soft': primary[1],
    '--crm-brand-secondary': secondary[5],
    '--crm-brand-secondary-soft': secondary[1],
    '--crm-brand-soft-overlay': alpha(primary[0], 92),
    '--crm-brand-overlay-strong': alpha(primary[6], 80),
    '--crm-brand-alpha-06': alpha(primary[6], 6),
    '--crm-brand-alpha-08': alpha(primary[6], 8),
    '--crm-brand-alpha-10': alpha(primary[6], 10),
    '--crm-brand-alpha-12': alpha(primary[6], 12),
    '--crm-brand-alpha-13': alpha(primary[6], 13),
    '--crm-brand-alpha-14': alpha(primary[6], 14),
    '--crm-brand-alpha-16': alpha(primary[6], 16),
    '--crm-brand-alpha-18': alpha(primary[6], 18),
    '--crm-brand-alpha-20': alpha(primary[6], 20),
    '--crm-brand-alpha-22': alpha(primary[6], 22),
    '--crm-brand-alpha-24': alpha(primary[6], 24),
    '--crm-brand-alpha-34': alpha(primary[6], 34),
    '--crm-brand-alpha-35': alpha(primary[6], 35),
    '--crm-brand-alpha-38': alpha(primary[6], 38),
    '--crm-brand-alpha-45': alpha(primary[6], 45),

    '--crm-accent-1-fg': primary[8],
    '--crm-accent-1-bg': alpha(primary[6], 12),
    '--crm-accent-1-border': alpha(primary[6], 24),
    '--crm-accent-2-fg': secondary[8],
    '--crm-accent-2-bg': alpha(secondary[6], 10),
    '--crm-accent-2-border': alpha(secondary[6], 24),
    '--crm-accent-3-fg': accentThree[8],
    '--crm-accent-3-bg': alpha(accentThree[6], 10),
    '--crm-accent-3-border': alpha(accentThree[6], 24),
    '--crm-accent-4-fg': accentFour[8],
    '--crm-accent-4-bg': alpha(accentFour[6], 12),
    '--crm-accent-4-border': alpha(accentFour[6], 32),

    '--crm-action-primary': primary[6],
    '--crm-action-primary-hover': primary[7],
    '--crm-action-primary-active': primary[8],
    '--crm-nav-active': `linear-gradient(135deg, ${primary[5]} 0%, ${primary[6]} 100%)`,
    '--crm-selection-bg': primary[1],
    '--crm-selection-border': primary[6],
    '--crm-focus-ring': primary[7],

    '--crm-surface-page': semanticBaseColors.background,
    '--crm-surface-page-alt': semanticBaseColors.backgroundAlt,
    '--crm-surface-card': semanticBaseColors.surface,
    '--crm-surface-subtle': semanticBaseColors.surfaceSubtle,
    '--crm-surface-muted': semanticBaseColors.surfaceMuted,
    '--crm-surface-disabled': semanticBaseColors.surfaceDisabled,
    '--crm-surface-overlay': alpha(semanticBaseColors.surface, 94),
    '--crm-surface-neutral-overlay': alpha(neutral[0], 95),
    '--crm-surface-subtle-overlay': alpha(semanticBaseColors.surfaceSubtle, 98),
    '--crm-surface-subtle-alpha': alpha(semanticBaseColors.surfaceSubtle, 80),
    '--crm-surface-raised-alpha': alpha(semanticBaseColors.surface, 80),
    '--crm-surface-page-alpha-55': alpha(semanticBaseColors.background, 55),
    '--crm-surface-page-alpha-72': alpha(semanticBaseColors.background, 72),
    '--crm-surface-page-alpha-74': alpha(semanticBaseColors.background, 74),
    '--crm-surface-page-alpha-76': alpha(semanticBaseColors.background, 76),
    '--crm-surface-page-alpha-88': alpha(semanticBaseColors.background, 88),
    '--crm-surface-page-alpha-90': alpha(semanticBaseColors.background, 90),
    '--crm-surface-page-alpha-92': alpha(semanticBaseColors.background, 92),
    '--crm-surface-page-alpha-96': alpha(semanticBaseColors.background, 96),
    '--crm-surface-card-alpha-08': alpha(semanticBaseColors.surface, 8),
    '--crm-surface-card-alpha-24': alpha(semanticBaseColors.surface, 24),
    '--crm-surface-card-alpha-72': alpha(semanticBaseColors.surface, 72),
    '--crm-surface-card-alpha-74': alpha(semanticBaseColors.surface, 74),
    '--crm-surface-card-alpha-76': alpha(semanticBaseColors.surface, 76),
    '--crm-surface-card-alpha-78': alpha(semanticBaseColors.surface, 78),
    '--crm-surface-card-alpha-84': alpha(semanticBaseColors.surface, 84),
    '--crm-surface-card-alpha-90': alpha(semanticBaseColors.surface, 90),
    '--crm-surface-card-alpha-92': alpha(semanticBaseColors.surface, 92),
    '--crm-surface-card-alpha-94': alpha(semanticBaseColors.surface, 94),
    '--crm-surface-card-alpha-95': alpha(semanticBaseColors.surface, 95),
    '--crm-surface-card-alpha-96': alpha(semanticBaseColors.surface, 96),
    '--crm-surface-card-alpha-97': alpha(semanticBaseColors.surface, 97),
    '--crm-surface-card-alpha-98': alpha(semanticBaseColors.surface, 98),
    '--crm-surface-card-alpha-99': alpha(semanticBaseColors.surface, 99),

    '--crm-border-default': semanticBaseColors.border,
    '--crm-border-muted': semanticBaseColors.borderMuted,
    '--crm-border-strong': semanticBaseColors.borderStrong,
    '--crm-text-heading': semanticBaseColors.textStrong,
    '--crm-text-primary': semanticBaseColors.text,
    '--crm-text-secondary': semanticBaseColors.muted,
    '--crm-text-disabled': semanticBaseColors.textDisabled,
    '--crm-text-inverse': semanticBaseColors.surface,

    '--crm-shadow-subtle': alpha(semanticBaseColors.text, 3),
    '--crm-shadow-soft': alpha(semanticBaseColors.text, 4),
    '--crm-shadow-card': alpha(semanticBaseColors.text, 6),
    '--crm-shadow-strong': alpha(semanticBaseColors.textStrong, 13),

    '--crm-motion-duration-fast': '120ms',
    '--crm-motion-duration-standard': '140ms',
    '--crm-motion-duration-continuous': '1400ms',
    '--crm-motion-easing-functional': 'ease',
    '--crm-motion-easing-continuous': 'ease-in-out',

    '--crm-status-success': semanticBaseColors.success,
    '--crm-status-success-fg': semanticBaseColors.successFg,
    '--crm-status-success-bg': alpha(semanticBaseColors.success, 12),
    '--crm-status-success-border': alpha(semanticBaseColors.success, 24),
    '--crm-status-warning': semanticBaseColors.warning,
    '--crm-status-warning-fg': semanticBaseColors.warningFg,
    '--crm-status-warning-bg': alpha(semanticBaseColors.warning, 12),
    '--crm-status-warning-border': alpha(semanticBaseColors.warning, 24),
    '--crm-status-danger': semanticBaseColors.danger,
    '--crm-status-danger-fg': semanticBaseColors.dangerFg,
    '--crm-status-danger-bg': alpha(semanticBaseColors.danger, 10),
    '--crm-status-danger-border': alpha(semanticBaseColors.danger, 30),
    '--crm-status-info': semanticBaseColors.info,
    '--crm-status-info-fg': semanticBaseColors.infoFg,
    '--crm-status-info-bg': alpha(semanticBaseColors.info, 10),
    '--crm-status-info-border': alpha(semanticBaseColors.info, 24),
    '--crm-status-neutral': semanticBaseColors.scheduleSlate,
    '--crm-status-neutral-fg': semanticBaseColors.neutralFg,
    '--crm-status-neutral-bg': alpha(semanticBaseColors.scheduleSlate, 11),
    '--crm-status-neutral-border': alpha(semanticBaseColors.scheduleSlate, 30),

    '--crm-auth-action': semanticBaseColors.authAction,
    '--crm-auth-action-hover': semanticBaseColors.authActionHover,
    '--crm-auth-action-active': semanticBaseColors.authActionActive,
    '--crm-auth-text': semanticBaseColors.authText,
    '--crm-auth-muted': semanticBaseColors.authMuted,
    '--crm-auth-icon-muted': semanticBaseColors.authIconMuted,
    '--crm-auth-border': semanticBaseColors.authBorder,
    '--crm-auth-border-alpha': alpha(semanticBaseColors.authBorder, 92),
    '--crm-auth-focus-ring': alpha(semanticBaseColors.authActionHover, 18),
    '--crm-auth-focus-ring-strong': alpha(semanticBaseColors.authActionHover, 24),
    '--crm-auth-solid-background': semanticBaseColors.authSolidBackground,
    '--crm-auth-overlay-edge': alpha('black', 22),
    '--crm-auth-overlay-image-soft': alpha(semanticBaseColors.authSolidBackground, 18),
    '--crm-auth-overlay-image-mid': alpha(semanticBaseColors.authSolidBackground, 70),
    '--crm-auth-overlay-image-start': alpha(semanticBaseColors.authSolidBackground, 92),
    '--crm-auth-overlay-image-tablet-start': alpha(semanticBaseColors.authSolidBackground, 74),
    '--crm-auth-overlay-image-tablet-mid': alpha(semanticBaseColors.authSolidBackground, 50),
    '--crm-auth-overlay-image-mobile-start': alpha(semanticBaseColors.authSolidBackground, 62),
    '--crm-auth-overlay-image-mobile-end': alpha(semanticBaseColors.authSolidBackground, 28),
    '--crm-auth-overlay-image-mobile-strong': alpha(semanticBaseColors.authSolidBackground, 84),
    '--crm-auth-overlay-solid-start': alpha(semanticBaseColors.authSolidBackground, 96),
    '--crm-auth-overlay-solid-end': alpha(semanticBaseColors.authSolidBackground, 88),
  }
}
